const KANJI = {
  N5: [
    // Nature & Elements
    { kanji: "山", kun: "やま", on: "サン", imi: "やま", en: "mountain", group: "Nature", mnemonic: "A picture of a mountain with a tall central peak and two shorter side peaks." },
    { kanji: "川", kun: "かわ", on: "セン", imi: "かわ", en: "river", group: "Nature", mnemonic: "Three parallel flowing lines representing the banks and current of a river." },
    { kanji: "田", kun: "た", on: "デン", imi: "た", en: "rice field", group: "Nature", mnemonic: "A square piece of land partitioned into four equal farming plots." },
    { kanji: "日", kun: "ひ・び", on: "ニチ・ニ・ジツ", imi: "ひ", en: "sun / day", group: "Nature", mnemonic: "A rectangular sun with a sunspot or horizon line drawn through the middle." },
    { kanji: "月", kun: "つき", on: "ゲツ・ガツ", imi: "つき", en: "moon / month", group: "Nature", mnemonic: "A crescent moon shaped with two atmospheric clouds sweeping across it." },
    { kanji: "火", kun: "ひ", on: "カ", imi: "ひ", en: "fire", group: "Nature", mnemonic: "A central campfire flame with two smaller sparks flying off the sides." },
    { kanji: "水", kun: "みず", on: "スイ", imi: "みず", en: "water", group: "Nature", mnemonic: "A central splash of water with droplets rippling outward." },
    { kanji: "木", kun: "き", on: "モク", imi: "き", en: "tree", group: "Nature", mnemonic: "A vertical trunk crossing a horizontal branch, with two roots digging into the earth." },
    { kanji: "金", kun: "かね", on: "キン", imi: "きん・かね", en: "gold / money", group: "Nature", mnemonic: "Golden nuggets hidden deep inside a mountain (under the top 'roof')." },
    { kanji: "土", kun: "つち", on: "ド・ト", imi: "つち", en: "soil", group: "Nature", mnemonic: "A tiny plant sprout breaking horizontally through the topsoil." },
    { kanji: "雨", kun: "あめ", on: "ウ", imi: "あめ", en: "rain", group: "Nature", mnemonic: "Looking out a window as drops of water fall from a storm cloud." },
    { kanji: "天", kun: "", on: "テン", imi: "てん", en: "heaven", group: "Nature", mnemonic: "A grand person (大) raising their arms all the way up to heaven." },
    { kanji: "気", kun: "", on: "キ", imi: "き", en: "spirit / air", group: "Nature", mnemonic: "Swirling steam rising from cooking rice, giving energy and spirit." },
    { kanji: "花", kun: "はな", on: "カ", imi: "はな", en: "flower", group: "Nature", mnemonic: "A botanical grass top (艹) that transforms (化) beautifully into a flower." },
    { kanji: "国", kun: "くに", on: "コク", imi: "くに", en: "country", group: "Nature", mnemonic: "A powerful king (王) holding jewels inside guarded borders (口)." },

    // Numbers
    { kanji: "一", kun: "ひとつ", on: "イチ・イッ", imi: "いち", en: "one", group: "Numbers", mnemonic: "A single, simple horizontal stroke." },
    { kanji: "二", kun: "ふたつ", on: "ニ", imi: "に", en: "two", group: "Numbers", mnemonic: "Two horizontal strokes." },
    { kanji: "三", kun: "みっつ", on: "サン", imi: "さん", en: "three", group: "Numbers", mnemonic: "Three horizontal strokes." },
    { kanji: "四", kun: "よっつ・よん・よ", on: "シ", imi: "よん", en: "four", group: "Numbers", mnemonic: "A box shaped with four sharp corners containing curtains inside." },
    { kanji: "五", kun: "いつつ", on: "ゴ", imi: "ご", en: "five", group: "Numbers", mnemonic: "Five distinct intersecting lines stacked together." },
    { kanji: "六", kun: "むっつ", on: "ロク・ロッ", imi: "ろく", en: "six", group: "Numbers", mnemonic: "A star-like figure with legs spread wide, totaling six points." },
    { kanji: "七", kun: "ななつ", on: "シチ", imi: "なな", en: "seven", group: "Numbers", mnemonic: "Looks similar to an upside-down 'L' or a '7' sliced through the middle." },
    { kanji: "八", kun: "やっつ", on: "ハチ・ハッ", imi: "はち", en: "eight", group: "Numbers", mnemonic: "Two lines parting ways, dividing into eight pieces." },
    { kanji: "九", kun: "ここのつ", on: "キュウ", imi: "きゅう", en: "nine", group: "Numbers", mnemonic: "Looks like a person doing pushups — striving for nine reps." },
    { kanji: "十", kun: "とお", on: "ジュウ・ジュッ・ジッ", imi: "じゅう", en: "ten", group: "Numbers", mnemonic: "A cross, easily remembered as the Roman numeral for ten (X) rotated upright." },
    { kanji: "百", kun: "", on: "ヒャク", imi: "ひゃく", en: "hundred", group: "Numbers", mnemonic: "One (一) drop of white (白) purity is worth a hundred." },
    { kanji: "千", kun: "ち", on: "セン", imi: "せん", en: "thousand", group: "Numbers", mnemonic: "Ten (十) wearing a heavy tilted hat (drop) to signify a massive thousand." },
    { kanji: "万", kun: "", on: "マン・バン", imi: "まん", en: "ten thousand", group: "Numbers", mnemonic: "A grand sweeping sword stroke slicing through the air for ten thousand points." },

    // Time & Money
    { kanji: "円", kun: "", on: "エン", imi: "まる・えん", en: "circle / yen", group: "Time & Money", mnemonic: "A perfectly framed box displaying a round coin inside." },
    { kanji: "年", kun: "とし", on: "ネン", imi: "ねん・とし", en: "year / age", group: "Time & Money", mnemonic: "A horse leaping over barriers to finish the year strong." },
    { kanji: "半", kun: "", on: "ハン", imi: "はんぶん", en: "half", group: "Time & Money", mnemonic: "A vertical line slicing evenly down to split the two top halves." },
    { kanji: "分", kun: "わける・わかる", on: "ブン・フン", imi: "ふん・ぶん", en: "minute / divide", group: "Time & Money", mnemonic: "A sharp knife (刀) to divide things into eight (八) equal pieces." },
    { kanji: "時", kun: "とき", on: "ジ", imi: "じかん", en: "time / hour", group: "Time & Money", mnemonic: "The sun (日) ticking past a towering temple (寺) to track the time." },
    { kanji: "週", kun: "", on: "シュウ", imi: "しゅう", en: "week", group: "Time & Money", mnemonic: "Going (辶) on a journey that circles perfectly around, taking one week." },
    { kanji: "午", kun: "", on: "ゴ", imi: "ひる", en: "noon", group: "Time & Money", mnemonic: "A sundial post showing the sun casting no shadow exactly at noon." },
    { kanji: "今", kun: "いま", on: "コン", imi: "いま", en: "now", group: "Time & Money", mnemonic: "A ticking clock placed neatly under the roof; the time is now." },

    // Directions & Position
    { kanji: "上", kun: "うえ・あがる", on: "ジョウ", imi: "うえ", en: "above / up", group: "Directions", mnemonic: "A vertical indicator standing above the flat baseline." },
    { kanji: "下", kun: "した・さがる", on: "カ・ゲ", imi: "した", en: "below / down", group: "Directions", mnemonic: "A vertical indicator dropping under the flat baseline." },
    { kanji: "中", kun: "なか", on: "チュウ・ジュウ", imi: "なか", en: "middle / inside", group: "Directions", mnemonic: "A sword striking straight through the middle of a target box." },
    { kanji: "前", kun: "まえ", on: "ゼン", imi: "まえ", en: "front / before", group: "Directions", mnemonic: "A butcher using a sharp knife (刂) in front of the hanging meat (月)." },
    { kanji: "後", kun: "うしろ・あと", on: "ゴ・ゴウ", imi: "うしろ・あと", en: "back / after", group: "Directions", mnemonic: "Two people walking (彳) dragging a thread behind them, lagging after." },
    { kanji: "外", kun: "そと", on: "ガイ", imi: "そと", en: "outside", group: "Directions", mnemonic: "Going outside in the evening (夕) to smoke." },
    { kanji: "左", kun: "ひだり", on: "サ", imi: "ひだり", en: "left", group: "Directions", mnemonic: "A hand holding an industrial tool (工) firmly in the left grip." },
    { kanji: "右", kun: "みぎ", on: "ウ・ユウ", imi: "みぎ", en: "right", group: "Directions", mnemonic: "A hand covering the mouth (口) — a gesture of the right hand." },
    { kanji: "東", kun: "ひがし", on: "トウ", imi: "ひがし", en: "east", group: "Directions", mnemonic: "The bright sun (日) rising directly behind a tree (木) in the east." },
    { kanji: "西", kun: "にし", on: "サイ・セイ", imi: "にし", en: "west", group: "Directions", mnemonic: "A tired bird settling into its boxed nest as the sun sets in the west." },
    { kanji: "南", kun: "みなみ", on: "ナン", imi: "みなみ", en: "south", group: "Directions", mnemonic: "An open southern gateway allowing the warm breeze to enter." },
    { kanji: "北", kun: "きた", on: "ホク・ホッ", imi: "きた", en: "north", group: "Directions", mnemonic: "Two people sitting back-to-back to block out the freezing north wind." },

    // People & Family
    { kanji: "人", kun: "ひと", on: "ジン・ニン", imi: "ひと", en: "person", group: "People", mnemonic: "Two legs walking confidently forward." },
    { kanji: "子", kun: "こ", on: "シ", imi: "こども", en: "child", group: "People", mnemonic: "A baby tightly swaddled with its tiny arms sticking out horizontally." },
    { kanji: "女", kun: "おんな", on: "ジョ", imi: "おんな", en: "woman", group: "People", mnemonic: "A woman gracefully bowing or crossing her legs while walking." },
    { kanji: "男", kun: "おとこ", on: "ダン・ナン", imi: "おとこ", en: "man", group: "People", mnemonic: "Heavy physical power (力) used to toil in the rice field (田)." },
    { kanji: "父", kun: "ちち", on: "フ", imi: "ちち", en: "father", group: "People", mnemonic: "Two disciplinary axes or canes crossed, held by a strict father." },
    { kanji: "母", kun: "はは", on: "ボ", imi: "はは", en: "mother", group: "People", mnemonic: "A woman's form with two dots emphasizing a mother nursing." },
    { kanji: "名", kun: "な", on: "メイ", imi: "なまえ", en: "name", group: "People", mnemonic: "Using your mouth (口) in the dark evening (夕) to shout your name." },

    // Body
    { kanji: "目", kun: "め", on: "モク", imi: "め", en: "eye", group: "Body", mnemonic: "An eyeball rotated vertically with two iris lines inside." },
    { kanji: "口", kun: "くち", on: "コウ", imi: "くち", en: "mouth", group: "Body", mnemonic: "A wide-open, square mouth ready to speak or eat." },
    { kanji: "耳", kun: "みみ", on: "ジ", imi: "みみ", en: "ear", group: "Body", mnemonic: "A side-profile of an ear, showing the inner cartilage ridges." },
    { kanji: "手", kun: "て", on: "シュ", imi: "て", en: "hand", group: "Body", mnemonic: "The lines trace the palm and fingers of an outstretched hand." },
    { kanji: "足", kun: "あし・たりる", on: "ソク", imi: "あし", en: "leg / foot", group: "Body", mnemonic: "A square 'mouth' representing the kneecap connected to a leg stepping out." },
    { kanji: "力", kun: "ちから", on: "リョク・リキ", imi: "ちから", en: "power / strength", group: "Body", mnemonic: "A heavily flexed bicep stretching downward with immense power." },

    // Education & Society
    { kanji: "先", kun: "さき", on: "セン", imi: "さき・まえ", en: "previous / ahead", group: "Society", mnemonic: "The legs (bottom) moving ahead of the earth/ground (top) to be first." },
    { kanji: "生", kun: "うまれる・いきる", on: "セイ", imi: "うまれる・いきる", en: "be born / live", group: "Society", mnemonic: "A strong green seedling sprouting out of the earth to live." },
    { kanji: "学", kun: "まなぶ", on: "ガク・ガッ", imi: "べんきょうする", en: "study / learn", group: "Society", mnemonic: "A young child (子) sitting under a schoolhouse roof studying." },
    { kanji: "校", kun: "", on: "コウ", imi: "がっこう", en: "school", group: "Society", mnemonic: "A wooden tree (木) next to a communal building where students mingle (交)." },
    { kanji: "友", kun: "とも", on: "ユウ", imi: "ともだち", en: "friend", group: "Society", mnemonic: "Two right hands reaching out from different directions to clasp in friendship." },
    { kanji: "本", kun: "もと", on: "ホン・ボン", imi: "ほん・もと", en: "book / origin", group: "Society", mnemonic: "A horizontal stroke marks the root or base of the tree (木)." },
    { kanji: "毎", kun: "", on: "マイ", imi: "まい", en: "every", group: "Society", mnemonic: "A person wearing a special hat every single day." },
    { kanji: "何", kun: "なに・なん", on: "", imi: "なに", en: "what", group: "Society", mnemonic: "A person (イ) carrying a heavy load (可), asking 'What is this?'" },
    { kanji: "会", kun: "あう", on: "カイ", imi: "あう", en: "meet", group: "Society", mnemonic: "Two people coming together under a unified roof to meet." },
    { kanji: "社", kun: "", on: "シャ", imi: "かいしゃ・やしろ", en: "company / shrine", group: "Society", mnemonic: "A spiritual altar (礻) grounded in the earth (土), representing a shrine or firm." },
    { kanji: "店", kun: "みせ", on: "テン", imi: "みせ", en: "shop / store", group: "Society", mnemonic: "A fortune-teller operating a booth inside a roofed shop." },
    { kanji: "駅", kun: "", on: "エキ", imi: "えき", en: "station", group: "Society", mnemonic: "A trusty horse (馬) pausing its journey at the measurement (尺) station." },

    // Animals
    { kanji: "牛", kun: "うし", on: "ギュウ", imi: "うし", en: "cow", group: "Animals", mnemonic: "A central line drawn through an animal with two distinct horns at the top." },
    { kanji: "馬", kun: "うま", on: "バ", imi: "うま", en: "horse", group: "Animals", mnemonic: "A majestic horse galloping with a flowing mane and four legs at the base." },
    { kanji: "魚", kun: "さかな", on: "ギョ", imi: "さかな", en: "fish", group: "Animals", mnemonic: "A pointy fish head, scaly body, and four fin strokes at the bottom." },
    { kanji: "貝", kun: "かい", on: "", imi: "かい", en: "shellfish", group: "Animals", mnemonic: "A detailed eye (目) peering out of a clam with two shell-legs holding it up." },

    // Objects & Places
    { kanji: "車", kun: "くるま", on: "シャ", imi: "くるま", en: "car / vehicle", group: "Objects", mnemonic: "A top-down blueprint of a carriage with wheels, an axle, and a cabin." },
    { kanji: "門", kun: "", on: "モン", imi: "もん", en: "gate", group: "Objects", mnemonic: "Two swinging saloon doors functioning as an entry gate." },
    { kanji: "道", kun: "みち", on: "ドウ", imi: "みち", en: "road / street", group: "Objects", mnemonic: "The leader (首) stepping onto the paved path (辶) — a road." },

    // Verbs & Actions
    { kanji: "行", kun: "いく・おこなう", on: "コウ・ギョウ", imi: "いく", en: "go", group: "Verbs", mnemonic: "A bustling, four-way street intersection where people go." },
    { kanji: "来", kun: "くる・こない・きます", on: "ライ", imi: "くる", en: "come", group: "Verbs", mnemonic: "Two people gathering under a grand tree, telling others to come." },
    { kanji: "食", kun: "たべる", on: "ショク", imi: "たべる", en: "eat", group: "Verbs", mnemonic: "A person resting under a roof, lifting a spoon to eat their meal." },
    { kanji: "見", kun: "みる", on: "ケン", imi: "みる", en: "see / look", group: "Verbs", mnemonic: "A giant eye (目) growing legs so it can walk around and see." },
    { kanji: "入", kun: "はいる・いれる", on: "ニュウ", imi: "はいる・いれる", en: "enter / put in", group: "Verbs", mnemonic: "A pointed wedge entering or sliding into a narrow gap." },
    { kanji: "出", kun: "でる・だす", on: "シュツ・シュッ", imi: "でる・だす", en: "go out / take out", group: "Verbs", mnemonic: "Two jagged mountains stacked; stepping from one mountain to go out." },
    { kanji: "立", kun: "たつ", on: "リツ・リッ", imi: "たつ", en: "stand", group: "Verbs", mnemonic: "A person with arms stretched out, standing firmly on the ground." },
    { kanji: "書", kun: "かく", on: "ショ", imi: "かく", en: "write", group: "Verbs", mnemonic: "A hand holding a writing brush horizontally over a piece of paper." },
    { kanji: "言", kun: "いう", on: "ゲン・ゴン", imi: "いう", en: "say / speak", group: "Verbs", mnemonic: "Sound waves and words repeatedly tumbling out of a mouth (口)." },
    { kanji: "飲", kun: "のむ", on: "イン", imi: "のむ", en: "drink", group: "Verbs", mnemonic: "Eating food (食) but opening your mouth wide (欠) to drink the soup." },
    { kanji: "話", kun: "はなす・はなし", on: "ワ", imi: "はなす", en: "speak / talk", group: "Verbs", mnemonic: "Saying (言) words dynamically with your tongue (舌) to speak." },
    { kanji: "読", kun: "よむ", on: "ドク", imi: "よむ", en: "read", group: "Verbs", mnemonic: "Words (言) being gathered and sold (売) as stories to read." },
    { kanji: "語", kun: "かたる", on: "ゴ", imi: "ことば", en: "word / language", group: "Verbs", mnemonic: "Words (言) spoken carefully by five (五) mouths (口) to form a language." },
    { kanji: "間", kun: "あいだ・ま", on: "カン", imi: "あいだ", en: "between / interval", group: "Verbs", mnemonic: "The sun (日) shining brilliantly through the space between the gates (門)." },
    { kanji: "聞", kun: "きく・きこえる", on: "ブン", imi: "きく", en: "listen / hear", group: "Verbs", mnemonic: "Pressing an ear (耳) directly against the wooden gate (門) to listen." },
    { kanji: "買", kun: "かう", on: "バイ", imi: "かう", en: "buy", group: "Verbs", mnemonic: "Catching valuable shells (貝) under a net (罒) to use as money to buy." },
    { kanji: "休", kun: "やすむ", on: "キュウ", imi: "やすむ", en: "rest", group: "Verbs", mnemonic: "A tired person (イ) leaning against a shady tree (木) to rest." },

    // Descriptions
    { kanji: "白", kun: "しろ・しろい", on: "ハク", imi: "しろ", en: "white", group: "Descriptions", mnemonic: "A single, pure white sunbeam striking out of the sun (日)." },
    { kanji: "空", kun: "そら・ぞら", on: "クウ", imi: "そら・くう", en: "sky / empty", group: "Descriptions", mnemonic: "A cave (穴) carved out using a tool (工), leaving it entirely empty." },
    { kanji: "電", kun: "", on: "デン", imi: "でんき", en: "electricity", group: "Descriptions", mnemonic: "A dark rain cloud (雨) firing a sudden, sharp lightning bolt (electricity)." },
  ],

  N4: [
    // Places
    { kanji: "住", kun: "すむ", on: "ジュウ", imi: "すむ", en: "live", group: "Places", mnemonic: "A person (イ) living right next to their master (主)." },
    { kanji: "所", kun: "ところ・どころ", on: "ショ・ジョ", imi: "ばしょ", en: "place", group: "Places", mnemonic: "Using an axe (斤) to carve a wooden door (戸) for your place." },
    { kanji: "京", kun: "", on: "キョウ", imi: "みやこ", en: "capital", group: "Places", mnemonic: "A towering, multi-story pagoda representing the capital city." },
    { kanji: "都", kun: "みやこ", on: "ト・ツ", imi: "みやこ", en: "metropolis", group: "Places", mnemonic: "The person (者) thriving in the bustling city boundaries (阝)." },
    { kanji: "府", kun: "", on: "フ", imi: "ふ", en: "admin prefecture", group: "Places", mnemonic: "Inside a massive government building (广) handing (付) laws down." },
    { kanji: "県", kun: "", on: "ケン", imi: "けん", en: "prefecture", group: "Places", mnemonic: "An eye (目) inspecting a tree from a hanging hook to survey the prefecture." },
    { kanji: "市", kun: "いち", on: "シ", imi: "し・いち", en: "city", group: "Places", mnemonic: "A grand market towel (巾) waving above the city streets." },
    { kanji: "区", kun: "", on: "ク", imi: "く", en: "ward", group: "Places", mnemonic: "A localized box containing an 'X' to mark the exact ward." },
    { kanji: "町", kun: "まち", on: "チョウ", imi: "まち", en: "town", group: "Places", mnemonic: "A rice field (田) positioned beside a street sign (丁) in town." },
    { kanji: "村", kun: "むら", on: "ソン", imi: "むら", en: "village", group: "Places", mnemonic: "Trees (木) planted just an inch (寸) apart around the village." },
    { kanji: "院", kun: "", on: "イン", imi: "たてもの", en: "institution / hospital", group: "Places", mnemonic: "A complete enclosure (阝) sheltering a great institution — the hospital (病院)." },
    { kanji: "場", kun: "ば", on: "ジョウ", imi: "ば・ばしょ", en: "place / field", group: "Places", mnemonic: "The sun (日) rising over the earth (土) marks this open place or field." },
    { kanji: "橋", kun: "はし", on: "キョウ", imi: "はし", en: "bridge", group: "Places", mnemonic: "A towering wooden (木) arch (喬) spanning the water — a bridge." },
    { kanji: "工", kun: "", on: "コウ", imi: "こうじ・こうじょう", en: "craft / construction", group: "Places", mnemonic: "A ruler measuring between two beams — the mark of a craftsman at work." },
    { kanji: "公", kun: "", on: "コウ", imi: "おおやけ", en: "public", group: "Places", mnemonic: "Sharing something fairly (ム) under the open sky (八) — for the public." },
    { kanji: "交", kun: "まじわる", on: "コウ", imi: "まじわる・こうつう", en: "exchange / traffic", group: "Places", mnemonic: "A person crossing their arms at a junction — the crossroads of exchange." },
    { kanji: "建", kun: "たてる", on: "ケン", imi: "たてる・たてもの", en: "build / construct", group: "Places", mnemonic: "A brush (聿) drawing along the road (廴) — building something new." },

    // Descriptions
    { kanji: "明", kun: "あかるい", on: "メイ", imi: "あかるい・はっきり", en: "bright / clear", group: "Descriptions", mnemonic: "The sun (日) and the moon (月) shining together are incredibly bright." },
    { kanji: "暗", kun: "くらい", on: "アン", imi: "くらい", en: "dark", group: "Descriptions", mnemonic: "A booming sound (音) blocking out the sun (日), rendering it dark." },
    { kanji: "遠", kun: "とおい", on: "エン", imi: "とおい", en: "far", group: "Descriptions", mnemonic: "Walking (辶) along the road in flowing robes (袁) takes you far away." },
    { kanji: "近", kun: "ちかい", on: "キン", imi: "ちかい", en: "near", group: "Descriptions", mnemonic: "Walking (辶) with an axe (斤) swinging dangerously near you." },
    { kanji: "強", kun: "つよい", on: "キョウ", imi: "つよい", en: "strong", group: "Descriptions", mnemonic: "A highly taut, strong bow (弓) snapping a tough insect (虫)." },
    { kanji: "弱", kun: "よわい", on: "ジャク", imi: "よわい", en: "weak", group: "Descriptions", mnemonic: "Two fragile, broken bows (弓) held together by thin feathers (彡) are weak." },
    { kanji: "重", kun: "おもい", on: "ジュウ", imi: "おもい・だいじな", en: "heavy / important", group: "Descriptions", mnemonic: "A vehicle/car (車) groaning under stacks of heavy luggage." },
    { kanji: "軽", kun: "かるい", on: "ケイ", imi: "かるい", en: "light", group: "Descriptions", mnemonic: "A car (車) constructed purely of thin, delicate thread (圣) is extremely light." },
    { kanji: "太", kun: "ふとい", on: "タイ", imi: "ふとい", en: "fat / thick", group: "Descriptions", mnemonic: "A big person (大) with an extra belly roll (dot) making them fat." },
    { kanji: "細", kun: "ほそい・こまかい", on: "サイ", imi: "ほそい・こまかい", en: "slender / fine", group: "Descriptions", mnemonic: "A delicate silk thread (糸) woven meticulously through the field (田)." },
    { kanji: "特", kun: "", on: "トク・トッ", imi: "とくべつな", en: "special", group: "Descriptions", mnemonic: "A highly prized, special cow (牛) grazing at the temple (寺)." },
    { kanji: "別", kun: "わかれる", on: "ベツ", imi: "わかれる", en: "separate", group: "Descriptions", mnemonic: "A mouth (口) commanding a sharp knife (刂) to separate ties." },
    { kanji: "有", kun: "ある", on: "ユウ", imi: "ある", en: "exist / have", group: "Descriptions", mnemonic: "A physical hand tightly grasping meat (月), proving it exists." },
    { kanji: "便", kun: "たより", on: "ベン・ビン", imi: "べんり・びん", en: "convenience / mail", group: "Descriptions", mnemonic: "A person (イ) actively changing/updating (更) things for convenience." },
    { kanji: "利", kun: "", on: "リ", imi: "りえき", en: "profit / advantage", group: "Descriptions", mnemonic: "Using a knife (刂) to harvest the grain (禾) brings swift profit." },
    { kanji: "不", kun: "", on: "フ・ブ", imi: "〜ではない", en: "not- (prefix)", group: "Descriptions", mnemonic: "A bird soaring up into the sky, deciding not to come back." },
    { kanji: "元", kun: "もと", on: "ゲン・ガン", imi: "もと", en: "origin", group: "Descriptions", mnemonic: "Two strong, foundational legs acting as the origin of all movement." },
    { kanji: "好", kun: "すき", on: "コウ", imi: "すき", en: "like / fond", group: "Descriptions", mnemonic: "A woman (女) holding her beloved child (子) because she likes them." },
    { kanji: "低", kun: "ひくい", on: "テイ", imi: "ひくい", en: "low", group: "Descriptions", mnemonic: "A person (イ) bowing to the ground beneath a noble clan (氏), showing low status." },
    { kanji: "広", kun: "ひろい", on: "コウ", imi: "ひろい", en: "spacious / wide", group: "Descriptions", mnemonic: "A vast, sloping roof (广) expanding infinitely outward into spaciousness." },
    { kanji: "短", kun: "みじかい", on: "タン", imi: "みじかい", en: "short", group: "Descriptions", mnemonic: "An arrow (矢) placed next to a tiny bean (豆), emphasizing it is short." },
    { kanji: "良", kun: "よい", on: "リョウ", imi: "よい", en: "good", group: "Descriptions", mnemonic: "A single, good drop of nourishment cleanly dropping into the stomach." },
    { kanji: "悪", kun: "わるい", on: "アク", imi: "わるい", en: "bad", group: "Descriptions", mnemonic: "An inferior, secondary (亜) feeling in your heart (心) is inherently bad." },
    { kanji: "正", kun: "ただしい", on: "セイ・ショウ", imi: "ただしい", en: "correct / right", group: "Descriptions", mnemonic: "Coming to a hard stop (止) exactly at the one (一) correct line." },
    { kanji: "変", kun: "かわる・かえる", on: "ヘン", imi: "かわる・へんな", en: "change / strange", group: "Descriptions", mnemonic: "A tangled knot of thread altering and changing (夂) its strange shape." },
    { kanji: "安", kun: "やすい", on: "アン", imi: "やすい・あんぜん", en: "cheap / safe", group: "Descriptions", mnemonic: "A woman (女) resting peacefully under a roof (宀) — feeling safe and at ease." },
    { kanji: "高", kun: "たかい", on: "コウ", imi: "たかい・たかさ", en: "high / expensive", group: "Descriptions", mnemonic: "A tall pagoda towering above everything — high and expensive." },
    { kanji: "新", kun: "あたらしい", on: "シン", imi: "あたらしい", en: "new", group: "Descriptions", mnemonic: "An axe (斤) cutting fresh wood (木) under a tree — something brand new." },
    { kanji: "古", kun: "ふるい", on: "コ", imi: "ふるい", en: "old", group: "Descriptions", mnemonic: "Ten (十) mouths (口) passing down the same old story — ancient." },
    { kanji: "多", kun: "おおい", on: "タ", imi: "おおい", en: "many / much", group: "Descriptions", mnemonic: "Two moons (夕夕) stacked — so many evenings, so many things." },
    { kanji: "少", kun: "すくない・すこし", on: "ショウ", imi: "すくない", en: "few / little", group: "Descriptions", mnemonic: "A small pile of just four strokes — deliberately few." },
    { kanji: "長", kun: "ながい", on: "チョウ", imi: "ながい・おさ", en: "long / leader", group: "Descriptions", mnemonic: "A flowing robe trailing behind a long-haired elder — long." },
    { kanji: "同", kun: "おなじ", on: "ドウ", imi: "おなじ", en: "same", group: "Descriptions", mnemonic: "A shared mouth (口) inside the same enclosure (冂) — all the same." },
    { kanji: "速", kun: "はやい", on: "ソク", imi: "はやい・スピード", en: "fast / speed", group: "Descriptions", mnemonic: "Moving along a bundled path (辶+束) — fast and quickly." },
    { kanji: "遅", kun: "おそい", on: "チ", imi: "おそい・おくれる", en: "slow / late", group: "Descriptions", mnemonic: "Walking (辶) while carrying a rhinoceros (犀) on your back — slow and late." },
    { kanji: "早", kun: "はやい・はやく", on: "ソウ", imi: "はやい・あさはやく", en: "early / fast", group: "Descriptions", mnemonic: "The sun (日) barely peeking over the horizon (十) — arriving early." },
    { kanji: "次", kun: "つぎ", on: "ジ", imi: "つぎ", en: "next", group: "Descriptions", mnemonic: "Water (冫) and a yawn (欠) — waiting and yawning for what comes next." },
    { kanji: "去", kun: "さる", on: "キョ", imi: "すぎた・さる", en: "past / leave", group: "Descriptions", mnemonic: "Standing up (土) and going away (ム) — departing into the past." },

    // Colors
    { kanji: "赤", kun: "あかい", on: "セキ", imi: "あか", en: "red", group: "Colors", mnemonic: "A raging fire (灬) burning intensely under the earth (土) glows red." },
    { kanji: "青", kun: "あおい", on: "セイ", imi: "あお", en: "blue", group: "Colors", mnemonic: "Lush, growing vegetation bathed in the blue light of the moon (月)." },
    { kanji: "黒", kun: "くろい", on: "コク", imi: "くろ", en: "black", group: "Colors", mnemonic: "A village (里) scorched by a massive fire (灬) turning completely black." },
    { kanji: "黄", kun: "きいろい", on: "コウ・オウ", imi: "き・きいろ", en: "yellow", group: "Colors", mnemonic: "A field (田) on fire (灬) turns glowing yellow at harvest time." },
    { kanji: "茶", kun: "", on: "チャ・サ", imi: "ちゃいろ・おちゃ", en: "brown / tea", group: "Colors", mnemonic: "Leaves picked from a plant (艹) sprouting above a tree (木) and person — brewing tea." },
    { kanji: "緑", kun: "みどり", on: "リョク", imi: "みどり", en: "green", group: "Colors", mnemonic: "Silk threads (糸) dyed with fresh water pigment (彔) hint at verdant green." },

    // Arts & Travel
    { kanji: "映", kun: "うつす", on: "エイ", imi: "うつす", en: "reflect / project", group: "Arts", mnemonic: "The bright sun (日) sitting perfectly in the center (央) to reflect its light." },
    { kanji: "画", kun: "", on: "ガ・カク", imi: "え", en: "picture / drawing", group: "Arts", mnemonic: "Lush fields (田) neatly bordered by an elegant frame like a picture." },
    { kanji: "音", kun: "おと", on: "オン", imi: "おと", en: "sound", group: "Arts", mnemonic: "Standing proudly (立) on top of the sun (日) emitting a loud sound." },
    { kanji: "楽", kun: "たのしい", on: "ガク・ラク", imi: "たのしい・かんたん", en: "enjoyable / music", group: "Arts", mnemonic: "Sparkling white (白) lights decorated on a wooden tree (木) are enjoyable." },
    { kanji: "歌", kun: "うた・うたう", on: "カ", imi: "うた", en: "song", group: "Arts", mnemonic: "Two brothers standing side-by-side, yawning (欠) to project a loud song." },
    { kanji: "写", kun: "うつす", on: "シャ", imi: "うつす", en: "copy / photograph", group: "Arts", mnemonic: "Sitting under a roof (冖) producing and giving (与) a precise copy." },
    { kanji: "真", kun: "ま", on: "シン", imi: "ほんとう", en: "truth / real", group: "Arts", mnemonic: "Ten (十) vigilant eyes (目) focusing on the pedestal of truth." },
    { kanji: "旅", kun: "たび", on: "リョ", imi: "たび", en: "trip / travel", group: "Arts", mnemonic: "People clustering under a waving flag on a guided trip." },

    // Society & World
    { kanji: "世", kun: "よ", on: "セ・セイ", imi: "せかい・せだい", en: "world / generation", group: "Society", mnemonic: "Three connected branches symbolizing continuous generations in this world." },
    { kanji: "界", kun: "", on: "カイ", imi: "さかいめ", en: "boundary / world", group: "Society", mnemonic: "Farm fields (田) wedged (介) together perfectly to define a boundary." },
    { kanji: "主", kun: "おもな・ぬし", on: "シュ", imi: "おもな・しゅじん", en: "main / master", group: "Society", mnemonic: "A lamp flame (丶) standing on a king's pillar (王) — the master at the center." },
    { kanji: "民", kun: "", on: "ミン", imi: "ひとびと", en: "people / nation", group: "Society", mnemonic: "A person (ノ) with an eye struck shut (氏) — the common people." },

    // Work
    { kanji: "仕", kun: "つかえる", on: "シ", imi: "つかえる", en: "serve", group: "Work", mnemonic: "A person (イ) standing tall as a samurai (士) ready to serve." },
    { kanji: "事", kun: "こと", on: "ジ", imi: "こと", en: "matter / thing", group: "Work", mnemonic: "A busy hand grasping a stick through a box, managing a difficult matter." },
    { kanji: "銀", kun: "", on: "ギン", imi: "ぎん", en: "silver", group: "Work", mnemonic: "Pure, good (艮) metal (金) shining like silver." },
    { kanji: "員", kun: "", on: "イン", imi: "なかま", en: "member", group: "Work", mnemonic: "A mouth (口) on top of the shells (貝), counting every member." },
    { kanji: "医", kun: "", on: "イ", imi: "いがく", en: "medicine / doctor", group: "Work", mnemonic: "A quiver (匸) holding an arrow (矢) — the ancient doctor's healing tool." },
    { kanji: "者", kun: "もの", on: "シャ", imi: "ひと", en: "person / expert", group: "Work", mnemonic: "An elder person (老) speaking at a gathering — the recognized expert." },
    { kanji: "働", kun: "はたらく", on: "ドウ", imi: "はたらく", en: "work / labor", group: "Work", mnemonic: "A person (イ) using heavy (重) force and power (力) — working hard." },
    { kanji: "産", kun: "うむ", on: "サン", imi: "つくる", en: "produce / birth", group: "Work", mnemonic: "A person standing on fertile land (生) producing new things — birth and production." },
    { kanji: "業", kun: "", on: "ギョウ", imi: "わざ", en: "deed / industry", group: "Work", mnemonic: "Two crossed tree trunks (業) representing the industry of many hands." },

    // Nature
    { kanji: "林", kun: "はやし", on: "リン", imi: "はやし", en: "wood / grove", group: "Nature", mnemonic: "Two trees (木木) standing side by side make a grove." },
    { kanji: "森", kun: "もり", on: "シン", imi: "もり", en: "forest", group: "Nature", mnemonic: "Three trees (木木木) crowded together form a deep forest." },
    { kanji: "地", kun: "", on: "ジ・チ", imi: "じめん", en: "ground / earth", group: "Nature", mnemonic: "The earth (土) spiraling like a snake (也) underfoot — the ground." },
    { kanji: "池", kun: "いけ", on: "チ", imi: "いけ", en: "pond", group: "Nature", mnemonic: "Water (氵) coiling like a snake (也) into a quiet, round pond." },
    { kanji: "海", kun: "うみ", on: "カイ", imi: "うみ", en: "sea", group: "Nature", mnemonic: "Every (每) drop of water (氵) flows together to form the vast sea." },
    { kanji: "洋", kun: "", on: "ヨウ", imi: "おおきいうみ", en: "ocean / Western", group: "Nature", mnemonic: "Water (氵) so grand and endless (羊) it becomes the open ocean." },
    { kanji: "雪", kun: "ゆき", on: "セツ", imi: "ゆき", en: "snow", group: "Nature", mnemonic: "Rain (雨) sweeping (彐) softly down as white snow." },
    { kanji: "光", kun: "ひかり・ひかる", on: "コウ", imi: "ひかり", en: "light / shine", group: "Nature", mnemonic: "A person (儿) with a flame blazing on their head — glowing with light." },
    { kanji: "台", kun: "", on: "ダイ・タイ", imi: "だい", en: "platform / stand", group: "Nature", mnemonic: "A mouth (口) raised up on a stand (厶) to make a speech — a platform." },
    { kanji: "風", kun: "かぜ", on: "フウ", imi: "かぜ・ふう", en: "wind / style", group: "Nature", mnemonic: "An insect (虫) caught in a sail (凡) and blown away by the wind." },

    // Seasons & Weather
    { kanji: "季", kun: "", on: "キ", imi: "きせつ", en: "season", group: "Seasons", mnemonic: "Grain (禾) growing over a child (子) — the turning cycle of seasons." },
    { kanji: "節", kun: "ふし", on: "セツ", imi: "くぎり", en: "season / joint", group: "Seasons", mnemonic: "Bamboo (竹) jointing at the temple (即) — one segment per season." },
    { kanji: "春", kun: "はる", on: "シュン", imi: "はる", en: "spring", group: "Seasons", mnemonic: "Three plants (艹) sprouting over the sun (日) — the warmth of spring." },
    { kanji: "夏", kun: "なつ", on: "カ", imi: "なつ", en: "summer", group: "Seasons", mnemonic: "A person (夂) dancing beneath the blazing sun — joyful summer." },
    { kanji: "秋", kun: "あき", on: "シュウ", imi: "あき", en: "autumn", group: "Seasons", mnemonic: "Grain (禾) turning fiery (火) with the brilliant colors of autumn." },
    { kanji: "冬", kun: "ふゆ", on: "トウ", imi: "ふゆ", en: "winter", group: "Seasons", mnemonic: "Ice crystals (冫) hanging from a thread — things freeze in winter." },
    { kanji: "暑", kun: "あつい", on: "ショ", imi: "あつい", en: "hot", group: "Seasons", mnemonic: "The sun (日) blazing directly over a person (者) outdoors — sweltering hot." },
    { kanji: "寒", kun: "さむい", on: "カン", imi: "さむい", en: "cold", group: "Seasons", mnemonic: "A person (人) under a roof (宀) surrounded on all sides by ice — shivering cold." },
    { kanji: "暖", kun: "あたたかい", on: "ダン", imi: "あたたかい", en: "warm", group: "Seasons", mnemonic: "The sun (日) wrapping its warm arms (爰) around you — warm and cozy." },

    // Body & Health
    { kanji: "体", kun: "からだ", on: "タイ", imi: "からだ", en: "body", group: "Body", mnemonic: "A person (イ) carrying their core root (本) — the foundation of the body." },
    { kanji: "頭", kun: "あたま", on: "ズ", imi: "あたま", en: "head", group: "Body", mnemonic: "A round bean (豆) sitting atop the head page (頁) — your round head." },
    { kanji: "顔", kun: "かお", on: "ガン", imi: "かお", en: "face", group: "Body", mnemonic: "A colorfully patterned page (頁) showing all your features — your face." },
    { kanji: "首", kun: "くび", on: "シュ", imi: "くび・だいいちの", en: "neck / prime", group: "Body", mnemonic: "Hair above (ノ) and a nose/self (自) below — the neck connecting head to body." },
    { kanji: "心", kun: "こころ", on: "シン", imi: "こころ・きもち", en: "heart / feelings", group: "Body", mnemonic: "Three drops of blood pumping outward from the heart — the seat of feelings." },
    { kanji: "声", kun: "こえ", on: "セイ", imi: "こえ", en: "voice", group: "Body", mnemonic: "A scholar (士) grounding (土) their voice — calling out clearly." },
    { kanji: "病", kun: "やまい", on: "ビョウ", imi: "びょうき", en: "illness", group: "Body", mnemonic: "A person lying on a sickbed (疒) stricken by illness." },
    { kanji: "薬", kun: "くすり", on: "ヤク・ヤッ", imi: "くすり", en: "medicine / drug", group: "Body", mnemonic: "Medicinal grass (艹) that brings joy and ease (楽) — healing medicine." },
    { kanji: "科", kun: "", on: "カ", imi: "わけたもの", en: "category / dept", group: "Body", mnemonic: "Grain (禾) measured on a scale (斗) and sorted into departments." },

    // Time
    { kanji: "内", kun: "うち", on: "ナイ", imi: "うち", en: "inside / within", group: "Time", mnemonic: "A person (人) standing inside an enclosure (冂) — within." },
    { kanji: "朝", kun: "あさ", on: "チョウ", imi: "あさ", en: "morning", group: "Time", mnemonic: "The sun (日) peeking through the morning mist beside the moon (月) — dawn." },
    { kanji: "昼", kun: "ひる", on: "チュウ", imi: "ひる", en: "noon / daytime", group: "Time", mnemonic: "The sun (日) passing its highest point — midday." },
    { kanji: "夜", kun: "よる・よ", on: "ヤ", imi: "よる", en: "night", group: "Time", mnemonic: "A person sheltered under a roof as the dark side (亦) rises — night." },
    { kanji: "夕", kun: "ゆう", on: "", imi: "ゆうがた", en: "evening", group: "Time", mnemonic: "A half-moon crescent glimpsed at dusk — the evening hour." },
    { kanji: "方", kun: "かた・がた", on: "ホウ", imi: "ほうがく・ほうほう", en: "direction / way", group: "Time", mnemonic: "A compass needle pointing in a specific direction or way." },
    { kanji: "晩", kun: "", on: "バン", imi: "よる", en: "late evening", group: "Time", mnemonic: "The sun (日) disappearing as a person (免) runs free — late evening." },
    { kanji: "計", kun: "はかる", on: "ケイ", imi: "はかる", en: "measure / plan", group: "Time", mnemonic: "Saying words (言) while counting (十) — planning and measuring time." },
    { kanji: "曜", kun: "", on: "ヨウ", imi: "かがやく", en: "day of week", group: "Time", mnemonic: "The sun (日) and a bright feathered bird (隹) marking off each day of the week." },
    { kanji: "以", kun: "", on: "イ", imi: "〜から", en: "since / from", group: "Time", mnemonic: "A person (人) walking with a tool — acting from a certain point on." },
    { kanji: "度", kun: "", on: "ド", imi: "ど・ひんど", en: "degree / frequency", group: "Time", mnemonic: "A hand (又) measuring with a wide ruler (广) — degrees of measure." },

    // Actions
    { kanji: "切", kun: "きる・きっ", on: "セツ", imi: "きる", en: "cut", group: "Actions", mnemonic: "Taking the number seven (七) and using a knife (刀) to cut it." },
    { kanji: "急", kun: "いそぐ", on: "キュウ", imi: "いそぐ・きゅうに", en: "hurry / suddenly", group: "Actions", mnemonic: "A heavy hand gripping your heart (心), forcing you to hurry in panic." },
    { kanji: "止", kun: "とまる", on: "シ", imi: "とまる", en: "stop", group: "Actions", mnemonic: "A single footstep pressed into the ground — stopped in its tracks." },
    { kanji: "歩", kun: "あるく", on: "ホ・ボ", imi: "あるく", en: "walk", group: "Actions", mnemonic: "A foot (止) stepping above another footprint (少) — walking step by step." },
    { kanji: "走", kun: "はしる", on: "ソウ", imi: "はしる", en: "run", group: "Actions", mnemonic: "A person (大) with soil (土) under their feet — running forward." },
    { kanji: "起", kun: "おきる・おこす", on: "キ", imi: "おきる", en: "get up / wake", group: "Actions", mnemonic: "A person rising (走) up over themselves (己) — getting up." },
    { kanji: "持", kun: "もつ", on: "ジ", imi: "もつ", en: "have / hold", group: "Actions", mnemonic: "A hand (手) gripping a temple (寺) — holding on firmly." },
    { kanji: "待", kun: "まつ", on: "タイ", imi: "まつ", en: "wait", group: "Actions", mnemonic: "A person walking (彳) and watching a temple (寺) — waiting patiently." },
    { kanji: "借", kun: "かりる", on: "シャク・シャッ", imi: "かりる", en: "borrow", group: "Actions", mnemonic: "A person (イ) with former (昔) debts — borrowing from the past." },
    { kanji: "貸", kun: "かす", on: "タイ", imi: "かす", en: "lend", group: "Actions", mnemonic: "A former (代) person's shells/money (貝) — lending from one's reserves." },
    { kanji: "始", kun: "はじまる・はじめる", on: "シ", imi: "はじまる", en: "begin / start", group: "Actions", mnemonic: "A woman (女) at a platform (台) marks the very beginning." },
    { kanji: "終", kun: "おわる", on: "シュウ", imi: "おわる", en: "end / finish", group: "Actions", mnemonic: "Silk thread (糸) coming to its end in winter (冬) — finishing." },
    { kanji: "活", kun: "", on: "カツ", imi: "いきいき", en: "lively / active", group: "Actions", mnemonic: "Water (氵) flowing with a tongue (舌) — lively and active." },
    { kanji: "回", kun: "まわす・まわる", on: "カイ", imi: "まわる", en: "turn / time", group: "Actions", mnemonic: "A spiral path inside a box — going around and around." },
    { kanji: "知", kun: "しる", on: "チ", imi: "しる", en: "know / be aware", group: "Actions", mnemonic: "An arrow (矢) shot into a mouth (口) hits exactly what you know." },
    { kanji: "思", kun: "おもう", on: "シ", imi: "おもう", en: "think / feel", group: "Actions", mnemonic: "The field (田) of your mind over the heart (心) — thinking deeply." },
    { kanji: "教", kun: "おしえる", on: "キョウ", imi: "おしえる", en: "teach / tell", group: "Actions", mnemonic: "Old filial ways (孝) struck with a rod (攵) — disciplined teaching." },
    { kanji: "使", kun: "つかう", on: "シ", imi: "つかう", en: "use", group: "Actions", mnemonic: "A person (イ) commanding an officer (吏) — putting someone to use." },
    { kanji: "作", kun: "つくる", on: "サク", imi: "つくる", en: "make / create", group: "Actions", mnemonic: "A person (イ) working with a saw (乍) — making something." },
    { kanji: "帰", kun: "かえる", on: "キ", imi: "かえる", en: "return home", group: "Actions", mnemonic: "A broom (帚) sweeping the path home — returning." },
    { kanji: "開", kun: "あける・ひらく", on: "カイ", imi: "あける", en: "open", group: "Actions", mnemonic: "Two hands pulling open the gate (門) — opening wide." },
    { kanji: "閉", kun: "しめる・とじる", on: "ヘイ", imi: "しめる", en: "close / shut", group: "Actions", mnemonic: "A bolt (才) thrown across the gate (門) — closing it shut." },
    { kanji: "乗", kun: "のる", on: "ジョウ", imi: "のる", en: "ride / board", group: "Actions", mnemonic: "A person jumping onto a tree (木) to ride it — boarding." },
    { kanji: "動", kun: "うごく", on: "ドウ", imi: "うごく", en: "move", group: "Actions", mnemonic: "Heavy/important (重) force and power (力) needed to move." },
    { kanji: "売", kun: "うる", on: "バイ", imi: "うる", en: "sell", group: "Actions", mnemonic: "A scholar hat (士) over an eye (目) — the merchant watching to sell." },
    { kanji: "送", kun: "おくる", on: "ソウ", imi: "おくる", en: "send", group: "Actions", mnemonic: "Walking (辶) together holding a torch — sending someone off." },
    { kanji: "受", kun: "うける", on: "ジュ", imi: "うける", en: "receive", group: "Actions", mnemonic: "Two hands reaching toward each other — receiving something." },
    { kanji: "習", kun: "ならう", on: "シュウ", imi: "ならう", en: "learn / practice", group: "Actions", mnemonic: "A young bird (羽) practicing over a white sheet (白) — learning by repetition." },
    { kanji: "考", kun: "かんがえる", on: "コウ", imi: "かんがえる", en: "think / consider", group: "Actions", mnemonic: "An old man (老) bent in thought with a hook at the end — deeply considering." },
    { kanji: "答", kun: "こたえる", on: "トウ", imi: "こたえる", en: "answer", group: "Actions", mnemonic: "A bamboo scroll (竹) joined with understanding (合) — the answer is within." },
    { kanji: "返", kun: "かえす", on: "ヘン", imi: "かえす", en: "return (something)", group: "Actions", mnemonic: "Walking back (辶) while reversing (反) — returning something." },
    { kanji: "転", kun: "ころぶ・まわる", on: "テン", imi: "ころぶ", en: "roll / fall / transfer", group: "Actions", mnemonic: "A car (車) that slips and turns (専) — rolling and transferring." },
    { kanji: "洗", kun: "あらう", on: "セン", imi: "あらう", en: "wash", group: "Actions", mnemonic: "Water (氵) flowing around the foot/ahead (先) — washing clean." },
    { kanji: "泳", kun: "およぐ", on: "エイ", imi: "およぐ", en: "swim", group: "Actions", mnemonic: "Water (氵) and forever flowing (永) — swimming endlessly." },
    { kanji: "着", kun: "きる・つく", on: "チャク", imi: "きる・つく", en: "wear / arrive", group: "Actions", mnemonic: "A sheep (羊) resting with an eye (目) — arriving clothed and settled." },
    { kanji: "払", kun: "はらう", on: "フツ", imi: "はらう", en: "pay", group: "Actions", mnemonic: "A hand (手) shaking out (ハ) coins — paying out." },
    { kanji: "通", kun: "とおる・かよう", on: "ツウ", imi: "とおる", en: "pass through / commute", group: "Actions", mnemonic: "Walking (辶) the same drum path (甬) every day — commuting through." },
    { kanji: "集", kun: "あつまる・あつめる", on: "シュウ", imi: "あつまる", en: "gather / collect", group: "Actions", mnemonic: "Many birds (隹) gathered on a tree (木) — a flock collecting." },
    { kanji: "決", kun: "きめる・きまる", on: "ケツ", imi: "きめる", en: "decide", group: "Actions", mnemonic: "Water (氵) made certain by a key (夬) — the matter is decided." },
    { kanji: "運", kun: "はこぶ", on: "ウン", imi: "はこぶ・うん", en: "carry / luck", group: "Actions", mnemonic: "Moving along (辶) with an army (軍) — carrying goods with luck." },
    { kanji: "向", kun: "むく・むける", on: "コウ", imi: "むく", en: "face toward / direction", group: "Actions", mnemonic: "A mouth (口) peeking out of a window (冂) — facing toward." },
    { kanji: "引", kun: "ひく", on: "イン", imi: "ひく", en: "pull", group: "Actions", mnemonic: "A bow (弓) drawn back with a stroke — pulling and drawing." },

    // Family
    { kanji: "家", kun: "いえ・や", on: "カ・ケ", imi: "いえ", en: "home / house", group: "Family", mnemonic: "A pig (豕) living under a roof (宀) — that's a home in ancient times." },
    { kanji: "族", kun: "", on: "ゾク", imi: "いちぞく", en: "tribe / family", group: "Family", mnemonic: "An arrow (矢) flying from a banner (方) — a clan rallying under one flag." },
    { kanji: "私", kun: "わたし・わたくし", on: "シ", imi: "わたし", en: "I / private", group: "Family", mnemonic: "Grain (禾) coiled and kept for oneself (ム) — my private share." },
    { kanji: "自", kun: "みずから", on: "シ・ジ", imi: "じぶん", en: "self / oneself", group: "Family", mnemonic: "A nose shape — in Japanese, pointing to one's nose means 'myself'." },
    { kanji: "親", kun: "おや・したしい", on: "シン", imi: "おや・したしい", en: "parent / close", group: "Family", mnemonic: "Standing on a tree (立+木), watching (見) closely — a parent's close attention." },
    { kanji: "両", kun: "", on: "リョウ", imi: "りょうほう", en: "both", group: "Family", mnemonic: "A cart with two wheels on both sides — representing both." },
    { kanji: "兄", kun: "あに", on: "ケイ・キョウ", imi: "あに", en: "elder brother", group: "Family", mnemonic: "A mouth (口) on top of legs (儿) — the elder brother who speaks first." },
    { kanji: "弟", kun: "おとうと", on: "ダイ", imi: "おとうと", en: "younger brother", group: "Family", mnemonic: "A bow (弓) with a stake and thread — the younger brother tied behind." },
    { kanji: "姉", kun: "あね", on: "シ", imi: "あね", en: "elder sister", group: "Family", mnemonic: "A woman (女) with a city (市) behind her — the elder sister who leads." },
    { kanji: "妹", kun: "いもうと", on: "マイ", imi: "いもうと", en: "younger sister", group: "Family", mnemonic: "A woman (女) not yet mature (未) — the younger sister." },
    { kanji: "夫", kun: "おっと", on: "フ・フウ", imi: "おっと", en: "husband", group: "Family", mnemonic: "A big person (大) with a topknot hairpin — a grown married man." },
    { kanji: "妻", kun: "つま", on: "サイ", imi: "つま", en: "wife", group: "Family", mnemonic: "A hand (又) held over a woman (女) — the devoted wife." },

    // Objects
    { kanji: "屋", kun: "や", on: "オク", imi: "やね", en: "roof / shop", group: "Objects", mnemonic: "A corpse (尸) resting over a reach (至) — a sheltering rooftop shop." },
    { kanji: "色", kun: "いろ", on: "ショク・シキ", imi: "いろ", en: "color", group: "Objects", mnemonic: "A kneeling person (巴) beside another (人) — showing vibrant color." },
    { kanji: "形", kun: "かたち", on: "ケイ・ギョウ", imi: "かたち", en: "shape / form", group: "Objects", mnemonic: "An open frame (开) stroked three times (彡) — a defined shape." },
    { kanji: "品", kun: "しな", on: "ヒン", imi: "しな", en: "goods / item", group: "Objects", mnemonic: "Three boxes (口口口) stacked — many goods on display." },
    { kanji: "服", kun: "", on: "フク", imi: "ふく・したがう", en: "clothes / obey", group: "Objects", mnemonic: "A moon/flesh (月) shape folded (卩) — clothes wrapping the body." },
    { kanji: "犬", kun: "いぬ", on: "ケン", imi: "いぬ", en: "dog", group: "Objects", mnemonic: "A big person (大) with a tiny dot — a loyal dog companion." },
    { kanji: "紙", kun: "かみ", on: "シ", imi: "かみ", en: "paper", group: "Objects", mnemonic: "Silk thread (糸) pressed flat by a clan (氏) — making paper." },
    { kanji: "図", kun: "", on: "ズ・ト", imi: "ず・ちず", en: "diagram / map", group: "Objects", mnemonic: "An enclosure (囗) containing a planned layout (×) — a diagram or map." },
    { kanji: "号", kun: "", on: "ゴウ", imi: "ごう・ばんごう", en: "number / name", group: "Objects", mnemonic: "A mouth (口) calling out from the sky (气) — announcing a number or name." },
    { kanji: "物", kun: "もの", on: "ブツ・モツ", imi: "もの", en: "thing / object", group: "Objects", mnemonic: "A cow (牛) and scattered pieces (勿) — all the things around us." },

    // Food
    { kanji: "肉", kun: "にく", on: "ニク", imi: "にく", en: "meat / flesh", group: "Food", mnemonic: "Two people (人人) packed inside an enclosure — meat packed tightly." },
    { kanji: "飯", kun: "めし", on: "ハン", imi: "めし・ごはん", en: "meal / cooked rice", group: "Food", mnemonic: "Eating (食) something turned and cooked (反) — a cooked rice meal." },
    { kanji: "野", kun: "の", on: "ヤ", imi: "の・やさい", en: "field / wild", group: "Food", mnemonic: "Rice fields (里) beside storage (予) — the wild open fields of vegetables." },
    { kanji: "菜", kun: "な", on: "サイ", imi: "やさい", en: "vegetable / greens", group: "Food", mnemonic: "A plant (艹) gathered by a hand (采) from the tree — fresh vegetables." },

    // Study & Society
    { kanji: "勉", kun: "", on: "ベン", imi: "べんきょう", en: "study diligently", group: "Study", mnemonic: "A rabbit (免) using force (力) to push through — studying hard." },
    { kanji: "英", kun: "", on: "エイ", imi: "えいご・すぐれた", en: "England / excellent", group: "Study", mnemonic: "Grass (艹) perfectly centered (央) — standing out as excellent." },
    { kanji: "文", kun: "ふみ", on: "ブン・モン", imi: "ぶんしょう", en: "sentence / writing", group: "Study", mnemonic: "A crossroads of strokes forming a literary mark — a written character." },
    { kanji: "字", kun: "", on: "ジ", imi: "もじ", en: "character / letter", group: "Study", mnemonic: "A child (子) learning under a roof (宀) — mastering characters." },
    { kanji: "数", kun: "かず", on: "スウ", imi: "かず", en: "number / count", group: "Study", mnemonic: "A woman (女) with a rice bundle (米) and a counting stick (攵) — counting carefully." },
    { kanji: "問", kun: "とう", on: "モン", imi: "もんだい", en: "question / problem", group: "Study", mnemonic: "A mouth (口) knocking at the gate (門) — asking a question." },
    { kanji: "題", kun: "", on: "ダイ", imi: "だいもく・もんだい", en: "subject / title", group: "Study", mnemonic: "A kingly truth (是) displayed above the head (頁) — the title on top." },
    { kanji: "番", kun: "", on: "バン", imi: "ばんごう・じゅんばん", en: "number / turn", group: "Study", mnemonic: "Rice fields (田) with scattered seeds (釆) — numbered plots taking their turn." },
    { kanji: "試", kun: "こころみる", on: "シ", imi: "こころみる・しけん", en: "try / test", group: "Study", mnemonic: "Words (言) tested with a ceremonial weapon (式) — formal attempts." },
    { kanji: "験", kun: "", on: "ケン", imi: "しけん・けいけん", en: "experience / exam", group: "Study", mnemonic: "A horse (馬) running through many hurdles (僉) — experiencing an exam." },
    { kanji: "研", kun: "とぐ", on: "ケン", imi: "けんきゅう", en: "research / polish", group: "Study", mnemonic: "A stone (石) ground open (开) — polishing away to research." },
    { kanji: "究", kun: "きわめる", on: "キュウ", imi: "きわめる", en: "investigate / complete", group: "Study", mnemonic: "A cave (穴) twisted nine ways (九) — searching to the ultimate depth." },
    { kanji: "注", kun: "そそぐ", on: "チュウ", imi: "そそぐ・ちゅうい", en: "pour / note / attention", group: "Study", mnemonic: "Water (氵) directed at a master (主) — pouring carefully, noting everything." },
    { kanji: "意", kun: "", on: "イ", imi: "い・きもち", en: "meaning / will / feeling", group: "Study", mnemonic: "A sound (音) over the heart (心) — the meaning felt deep inside." },
    { kanji: "味", kun: "あじ", on: "ミ", imi: "あじ・いみ", en: "taste / flavor / meaning", group: "Study", mnemonic: "A mouth (口) tasting the unknown (未) — savoring something new." },
    { kanji: "発", kun: "", on: "ハツ・ホッ", imi: "はっしゃ・でる", en: "start / emit / depart", group: "Study", mnemonic: "Legs rising (癶) as a bow (弓) is launched — departing, starting off." },
    { kanji: "代", kun: "かわる", on: "ダイ・タイ", imi: "かわり・じだい", en: "substitute / generation", group: "Study", mnemonic: "A person (イ) wielding a weapon (弋) — standing in as a substitute." },
  ]
};

function getKanjiGroups(level) {
  const seen = new Set();
  return (KANJI[level] || []).reduce((acc, k) => {
    if (!seen.has(k.group)) { seen.add(k.group); acc.push(k.group); }
    return acc;
  }, []);
}

function getKanjiByGroup(level, group) {
  const all = KANJI[level] || [];
  return group === 'all' ? all : all.filter(k => k.group === group);
}

function getKanjiGroupCount(level, group) {
  return getKanjiByGroup(level, group).length;
}
