const KANJI = {
  N5: [
    { kanji: "一", kun: "ひとつ", on: "イチ・イッ", imi: "いち", en: "one", group: "Numbers", mnemonic: "A single horizontal line." },
    { kanji: "二", kun: "ふたつ", on: "ニ", imi: "に", en: "two", group: "Numbers", mnemonic: "Two lines; the bottom line is longer." },
    { kanji: "三", kun: "みっつ", on: "サン", imi: "さん", en: "three", group: "Numbers", mnemonic: "Three lines; the middle line is the shortest." },
    { kanji: "口", kun: "くち", on: "コウ", imi: "くち", en: "mouth", group: "Body", mnemonic: "An empty square box representing an open mouth." },
    { kanji: "四", kun: "よっつ・よん・よ", on: "シ", imi: "よん", en: "four", group: "Numbers", mnemonic: "A square box with “legs” inside." },
    { kanji: "五", kun: "いつつ", on: "ゴ", imi: "ご", en: "five", group: "Numbers", mnemonic: "Horizontal line on top/bottom with a diagonal and “L” shape inside." },
    { kanji: "六", kun: "むっつ", on: "ロク・ロッ", imi: "ろく", en: "six", group: "Numbers", mnemonic: "A “lid” with a small horizontal dash on top and two “legs” below." },
    { kanji: "七", kun: "ななつ", on: "シチ", imi: "なな", en: "seven", group: "Numbers", mnemonic: "A horizontal line with a hook cutting through it; looks like a slanted 7." },
    { kanji: "八", kun: "やっつ", on: "ハチ・ハッ", imi: "はち", en: "eight", group: "Numbers", mnemonic: "Two separate diagonal strokes flaring outward; looks like a mountain or open legs." },
    { kanji: "九", kun: "ここのつ", on: "キュウ", imi: "きゅう", en: "nine", group: "Numbers", mnemonic: "A downward curve crossed by a hooked stroke; looks a bit like the letter “n” or “r.”" },
    { kanji: "千", kun: "ち", on: "セン", imi: "せん", en: "thousand", group: "Numbers", mnemonic: "A cross with a slanted dash on top; looks like a “plus” with a hat." },
    { kanji: "万", kun: "", on: "マン・バン", imi: "まん", en: "ten thousand", group: "Numbers", mnemonic: "A horizontal line with a hook shape and a diagonal line underneath." },
    { kanji: "円", kun: "", on: "エン", imi: "まる・えん", en: "circle / yen", group: "Time & Money", mnemonic: "A box with a “pot lid” shape inside; used for Japanese currency." },
    { kanji: "上", kun: "うえ・あがる", on: "ジョウ", imi: "うえ", en: "above / up", group: "Directions", mnemonic: "A vertical line on top of a horizontal line, with a small dash sticking out to the right." },
    { kanji: "下", kun: "した・さがる", on: "カ・ゲ", imi: "した", en: "below / down", group: "Directions", mnemonic: "A horizontal line with a vertical line hanging down and a small dash on the right." },
    { kanji: "人", kun: "ひと", on: "ジン・ニン", imi: "ひと", en: "person", group: "People", mnemonic: "Two strokes meeting at the top; looks like a pair of walking legs." },
    { kanji: "火", kun: "ひ", on: "カ", imi: "ひ", en: "fire", group: "Nature", mnemonic: "A “person” with two small sparks/dots on either side." },
    { kanji: "土", kun: "つち", on: "ド・ト", imi: "つち", en: "soil", group: "Nature", mnemonic: "A small “plus” sign sitting on a longer horizontal line; looks like a gravestone." },
    { kanji: "水", kun: "みず", on: "スイ", imi: "みず", en: "water", group: "Nature", mnemonic: "A central hooked vertical line with four smaller strokes splashing around it." },
    { kanji: "木", kun: "き", on: "モク", imi: "き", en: "tree", group: "Nature", mnemonic: "A cross with two diagonal “branches” at the bottom; looks like a tree with roots." },
    { kanji: "王", kun: "", on: "オウ", imi: "おう", en: "king", group: "People", mnemonic: "Three horizontal lines connected by a central vertical “staff.”" },
    { kanji: "玉", kun: "たま", on: "ギョク", imi: "たま", en: "jewel / ball", group: "Objects", mnemonic: "The “King” character with a small “drop” or dot on the bottom right." },
    { kanji: "国", kun: "くに", on: "コク", imi: "くに", en: "country", group: "Nature", mnemonic: "A “Jewel” enclosed inside a large box." },
    { kanji: "金", kun: "かね", on: "キン", imi: "きん・かね", en: "gold / money", group: "Nature", mnemonic: "A “human roof” on top, with a horizontal line and “dirt” below, plus two small diagonal dots inside." },
    { kanji: "休", kun: "やすむ", on: "キュウ", imi: "やすむ", en: "rest", group: "Verbs", mnemonic: "A “person” leaning against a “tree.”" },
    { kanji: "目", kun: "め", on: "モク", imi: "め", en: "eye", group: "Body", mnemonic: "A vertical rectangle with two horizontal lines inside; looks like an eye on its side." },
    { kanji: "見", kun: "みる", on: "ケン", imi: "みる", en: "see / look", group: "Verbs", mnemonic: "An “eye” on top of “person’s legs”." },
    { kanji: "耳", kun: "みみ", on: "ジ", imi: "みみ", en: "ear", group: "Body", mnemonic: "A tall rectangle with extra lines sticking out the sides; looks like a stylized ear." },
    { kanji: "止", kun: "とまる", on: "シ", imi: "とまる", en: "stop", group: "Verbs", mnemonic: "A vertical line with a “flag” on the right and a horizontal base; also means footprint." },
    { kanji: "足", kun: "あし・たりる", on: "ソク", imi: "あし", en: "leg / foot", group: "Body", mnemonic: "A “mouth” on top of the “stop” character." },
    { kanji: "正", kun: "ただしい", on: "セイ・ショウ", imi: "ただしい", en: "correct", group: "Descriptions", mnemonic: "A horizontal line on top of the “stop” character." },
    { kanji: "車", kun: "くるま", on: "シャ", imi: "くるま", en: "car / vehicle", group: "Objects", mnemonic: "A vertical “staff” cutting through two horizontal lines and a central “sun” box; looks like a top-down view of a cart." },
    { kanji: "手", kun: "て", on: "シュ", imi: "て", en: "hand", group: "Body", mnemonic: "A diagonal dash on top of the character for “two,” with a hooked vertical line cutting through." },
    { kanji: "子", kun: "こ", on: "シ", imi: "こども", en: "child", group: "People", mnemonic: "A horizontal stroke on top of a hooked line, crossed by another horizontal line; looks like a baby in swaddling clothes." },
    { kanji: "字", kun: "", on: "ジ", imi: "もじ", en: "character / letter", group: "Society", mnemonic: "A “house roof” with a “child” inside." },
    { kanji: "学", kun: "まなぶ", on: "ガク・ガッ", imi: "べんきょうする", en: "study / learn", group: "Society", mnemonic: "A complex crown shape with three dashes on top of a “house roof,” with a “child” at the bottom." },
    { kanji: "田", kun: "た", on: "デン", imi: "た", en: "rice field", group: "Nature", mnemonic: "A square box divided into four smaller squares; looks like a window or a divided plot of land." },
    { kanji: "力", kun: "ちから", on: "リョク・リキ", imi: "ちから", en: "power / strength", group: "Body", mnemonic: "A downward stroke with a hooked right turn, crossed by a curved diagonal slash; looks like a flexing arm." },
    { kanji: "男", kun: "おとこ", on: "ダン・ナン", imi: "おとこ", en: "man", group: "People", mnemonic: "A “Field” on top of “Strength”." },
    { kanji: "女", kun: "おんな", on: "ジョ", imi: "おんな", en: "woman", group: "People", mnemonic: "An angular zigzag crossed by a curved stroke, with a horizontal line cutting across the top; resembles a figure kneeling or striking a pose." },
    { kanji: "友", kun: "とも", on: "ユウ", imi: "ともだち", en: "friend", group: "Society", mnemonic: "Two overlapping crossed lines beneath a horizontal stroke; looks like two hands coming together." },
    { kanji: "父", kun: "ちち", on: "フ", imi: "ちち", en: "father", group: "People", mnemonic: "Two small dots on top of two crossing diagonal lines; looks like a pair of “grass clippers” under a mustache/eyebrows." },
    { kanji: "母", kun: "はは", on: "ボ", imi: "はは", en: "mother", group: "People", mnemonic: "A wide, jagged enclosure with a horizontal line cutting through the middle and two dots inside; visually similar to the “Woman” kanji but fuller." },
    { kanji: "毎", kun: "", on: "マイ", imi: "まい", en: "every", group: "Society", mnemonic: "A horizontal slash above the “Mother” character." },
    { kanji: "分", kun: "わける・わかる", on: "ブン・フン", imi: "ふん・ぶん", en: "minute / divide", group: "Time & Money", mnemonic: "An upside-down “V” shape sitting on top of a “Katana/Sword” shape; looks like a knife cutting something in half." },
    { kanji: "今", kun: "いま", on: "コン", imi: "いま", en: "now", group: "Time & Money", mnemonic: "A “human roof” shape at the top, a small horizontal dash, and an angular stroke at the bottom." },
    { kanji: "午", kun: "", on: "ゴ", imi: "ひる", en: "noon", group: "Time & Money", mnemonic: "A small horizontal slash on top of the character for “ten”." },
    { kanji: "年", kun: "とし", on: "ネン", imi: "ねん・とし", en: "year / age", group: "Time & Money", mnemonic: "A complex structure with a small horizontal dash on top, crossed by vertical and horizontal lines; looks similar to the “hang to dry” shape with extra strokes." },
    { kanji: "寺", kun: "てら", on: "ジ", imi: "てら", en: "temple", group: "Society", mnemonic: "“Dirt/Soil” sitting on top of the “small measurement” shape." },
    { kanji: "時", kun: "とき", on: "ジ", imi: "じかん", en: "time / hour", group: "Time & Money", mnemonic: "The “Sun” character positioned to the left of the “Temple” character." },
    { kanji: "小", kun: "ちいさい", on: "ショウ", imi: "ちいさい", en: "small", group: "Descriptions", mnemonic: "A central hooked vertical line flanked by two small dashes leaning outward." },
    { kanji: "大", kun: "おおきい", on: "ダイ", imi: "おおきい", en: "big", group: "Descriptions", mnemonic: "A horizontal line crossed by a person-shaped form beneath it; looks like a person standing with their arms stretched wide out." },
    { kanji: "犬", kun: "いぬ", on: "ケン", imi: "いぬ", en: "dog", group: "Animals", mnemonic: "The character for “Big” with an additional small drop or dash placed in the upper right quadrant." },
    { kanji: "半", kun: "", on: "ハン", imi: "はんぶん", en: "half", group: "Time & Money", mnemonic: "A horizontal line cutting through the middle of the “Ten” character, with two small dashes/legs flaring out at the top." },
    { kanji: "前", kun: "まえ", on: "ゼン", imi: "まえ", en: "front / before", group: "Directions", mnemonic: "A horizontal structure with two outward-flaring dots on top, the “Moon” character on the bottom left, and two vertical strokes on the bottom right." },
    { kanji: "来", kun: "くる・こない・きます", on: "ライ", imi: "くる", en: "come", group: "Verbs", mnemonic: "A horizontal line on top, two small dots beneath it, and an intersecting vertical line that flares out into two diagonal “branches” at the bottom; looks like a tree with extra marks near the top." },
    { kanji: "川", kun: "かわ", on: "セン", imi: "かわ", en: "river", group: "Nature", mnemonic: "Three vertical lines side-by-side; looks like water flowing between two banks." },
    { kanji: "山", kun: "やま", on: "サン", imi: "やま", en: "mountain", group: "Nature", mnemonic: "A central tall vertical line with an L-shape on the left and another shorter vertical line on the right; looks like three mountain peaks." },
    { kanji: "出", kun: "でる・だす", on: "シュツ・シュッ", imi: "でる・だす", en: "go out / take out", group: "Verbs", mnemonic: "A vertical line passing through two stacked, boxy “U” or “L” shapes; looks like two mountains stacked on top of each other." },
    { kanji: "入", kun: "はいる・いれる", on: "ニュウ", imi: "はいる・いれる", en: "enter / put in", group: "Verbs", mnemonic: "Two strokes leaning into each other; looks similar to the “Person” kanji but the right stroke starts higher and sweeps over the left stroke." },
    { kanji: "天", kun: "", on: "テン", imi: "てん", en: "heaven", group: "Nature", mnemonic: "A horizontal line resting on top of the character for “Big”; looks like a person standing with their arms out beneath the sky." },
    { kanji: "夕", kun: "ゆう", on: "", imi: "ゆうがた", en: "evening", group: "Nature", mnemonic: "A downward-curving stroke crossed by a hooked stroke with a dot inside; looks like the “Moon” character but with only one dot and a more slanted top." },
    { kanji: "名", kun: "な", on: "メイ", imi: "なまえ", en: "name", group: "People", mnemonic: "The “Evening” character on top of the “Mouth” character; refers to calling out names in the dark." },
    { kanji: "化", kun: "ばける", on: "カ", imi: "ばける", en: "change", group: "Verbs", mnemonic: "The “Person” shape on the left and a “Spoon” or “Ladle” shape on the right." },
    { kanji: "花", kun: "はな", on: "カ", imi: "はな", en: "flower", group: "Nature", mnemonic: "A “Grass” crown on top of the “Change” character." },
    { kanji: "竹", kun: "たけ", on: "チク", imi: "たけ", en: "bamboo", group: "Nature", mnemonic: "Two identical side-by-side structures, each consisting of a small diagonal dash on top of a vertical line; looks like stalks of bamboo with leaves." },
    { kanji: "早", kun: "はやい・はやく", on: "ソウ", imi: "はやい・あさはやく", en: "early / fast", group: "Time & Money", mnemonic: "A square “sun” box on top of a vertical line crossing a horizontal line; resembles a sun rising over the horizon or a flower on a stem." },
    { kanji: "草", kun: "くさ", on: "ソウ", imi: "くさ", en: "weeds / grass", group: "Nature", mnemonic: "A horizontal line crossed by two short vertical dashes on top, with the “early” character underneath it." },
    { kanji: "林", kun: "はやし", on: "リン", imi: "はやし", en: "wood / grove", group: "Nature", mnemonic: "Two tree shapes placed side-by-side." },
    { kanji: "森", kun: "もり", on: "シン", imi: "もり", en: "forest", group: "Nature", mnemonic: "Three tree shapes stacked together; one on top and two on the bottom." },
    { kanji: "交", kun: "まじわる", on: "コウ", imi: "まじわる・こうつう", en: "exchange / traffic", group: "Society", mnemonic: "A small dot/dash above a horizontal line, over two crossing strokes with small outward dashes; resembles a person standing with crossed legs under a hat." },
    { kanji: "校", kun: "", on: "コウ", imi: "がっこう", en: "school", group: "Society", mnemonic: "A tree shape on the left side, next to the “mingle/cross” character on the right." },
    { kanji: "言", kun: "いう", on: "GEN・GON", imi: "いう", en: "say / speak", group: "Verbs", mnemonic: "A small dot or dash on top of three horizontal lines, with a square box at the very bottom." },
    { kanji: "語", kun: "かたる", on: "ゴ", imi: "ことば", en: "word / language", group: "Verbs", mnemonic: "The “Word” character on the left, with the character for “Five” stacked on top of a square box on the right." },
    { kanji: "話", kun: "はなす・はなし", on: "ワ", imi: "はなす", en: "speak / talk", group: "Verbs", mnemonic: "The “Word” character on the left, with the character for “Thousand” stacked on top of a square box on the right." },
    { kanji: "売", kun: "うる", on: "バイ", imi: "うる", en: "sell", group: "Verbs", mnemonic: "A short horizontal line crossing a vertical line, placed over a “hat” shape, with two “legs” or swooping dashes underneath." },
    { kanji: "読", kun: "よむ", on: "ドク", imi: "よむ", en: "read", group: "Verbs", mnemonic: "The “Word” character on the left, next to the “Sell” character on the right." },
    { kanji: "本", kun: "もと", on: "ホン・ボン", imi: "ほん・もと", en: "book / origin", group: "Society", mnemonic: "The character for “Tree” with an extra horizontal line cutting through the lower trunk; resembles the roots of a tree." },
    { kanji: "文", kun: "ふみ", on: "ブン・モン", imi: "ぶんしょう", en: "sentence / writing", group: "Society", mnemonic: "A small dash/dot on top of a horizontal line, over a set of crossing diagonal strokes; looks like a person with their arms out and legs crossed/moving." },
    { kanji: "右", kun: "みぎ", on: "ウ・ユウ", imi: "みぎ", en: "right", group: "Directions", mnemonic: "A diagonal swoop crossing a horizontal line, with a square “Mouth” box placed underneath it." },
    { kanji: "左", kun: "ひだり", on: "サ", imi: "ひだり", en: "left", group: "Directions", mnemonic: "A horizontal line crossing a diagonal swoop, with an “I-beam” shaped structure placed underneath it." },
    { kanji: "立", kun: "たつ", on: "リツ・リッ", imi: "たつ", en: "stand", group: "Verbs", mnemonic: "A small horizontal dash on top of a horizontal line, supported by two small outward-pointing legs and a longer horizontal base." },
    { kanji: "音", kun: "おと", on: "オン", imi: "おと", en: "sound", group: "Arts", mnemonic: "The “Stand” character positioned on top of the “Sun” character." },
    { kanji: "門", kun: "", on: "モン", imi: "もん", en: "gate", group: "Objects", mnemonic: "A large frame consisting of two symmetrical door-like structures; looks like saloon doors or a classic gateway." },
    { kanji: "間", kun: "あいだ・ま", on: "カン", imi: "あいだ", en: "between / interval", group: "Verbs", mnemonic: "The “Gate” character with the “Sun” character placed inside the frame." },
    { kanji: "聞", kun: "きく・きこえる", on: "ブン", imi: "きく", en: "listen / hear", group: "Verbs", mnemonic: "The “Gate” character with the “Ear” character placed inside the frame." },
    { kanji: "生", kun: "うまれる・いきる", on: "セイ", imi: "うまれる・いきる", en: "be born / live", group: "Society", mnemonic: "A series of horizontal lines connected by a vertical “staff,” with a small diagonal dash on the top left; looks like a sprouting plant." },
    { kanji: "青", kun: "あおい", on: "セイ", imi: "あお", en: "blue", group: "Colors", mnemonic: "The “Life” character scrunched on top of the “Moon” character." },
    { kanji: "赤", kun: "あかい", on: "セキ", imi: "あか", en: "red", group: "Colors", mnemonic: "A “Soil” or “Dirt” character on top, with a “person’s legs” shape below that has two extra dots; resembles a person over a fire." },
    { kanji: "先", kun: "さき", on: "セン", imi: "さき・まえ", en: "previous / ahead", group: "Society", mnemonic: "A small diagonal dash on top of a horizontal line, over the “person’s legs” shape." },
    { kanji: "石", kun: "いし", on: "セキ", imi: "いし", en: "stone", group: "Nature", mnemonic: "A horizontal line and a sweeping diagonal stroke forming a “Cliff,” with a square “Mouth” box underneath it; looks like a rock falling from a cliff." },
    { kanji: "書", kun: "かく", on: "ショ", imi: "かく", en: "write", group: "Verbs", mnemonic: "A complex top structure with three horizontal lines and a vertical “staff,” sitting over a square “Mouth” box." },
    { kanji: "糸", kun: "いと", on: "シ", imi: "いと", en: "thread", group: "Objects", mnemonic: "A series of hooked, angular lines stacked on top of a central vertical line with two small outwardpointing dashes; looks like thread wrapped around a spool." },
    { kanji: "後", kun: "うしろ・あと", on: "ゴ・ゴウ", imi: "うしろ・あと", en: "back / after", group: "Directions", mnemonic: "A “walking man” shape on the left, with “thread” and a “legs/walking” shape on the right; looks like someone trailing behind." },
    { kanji: "気", kun: "", on: "キ", imi: "き", en: "spirit / air", group: "Nature", mnemonic: "A slanted “X” shape on top of a series of horizontal lines with a sweeping tail; resembles steam or moving air." },
    { kanji: "空", kun: "そら・ぞら", on: "クウ", imi: "そら・くう", en: "sky / empty", group: "Descriptions", mnemonic: "A “house roof” with two small dashes/eyes on top, and an “I-beam” structure underneath; looks like a vast opening or a clear sky." },
    { kanji: "高", kun: "たかい", on: "コウ", imi: "たかい・たかさ", en: "high / expensive", group: "Descriptions", mnemonic: "A “pot lid” on top, a small square “mouth,” and a larger square “mouth” enclosed within a box; looks like a multi-story building or tower." },
    { kanji: "何", kun: "なに・なん", on: "", imi: "なに", en: "what", group: "Society", mnemonic: "A “person” on the left and a “street sign/nail” structure over a “mouth” on the right." },
    { kanji: "町", kun: "まち", on: "チョウ", imi: "まち", en: "town", group: "Places", mnemonic: "A “field” on the left and a “street sign/nail” structure on the right." },
    { kanji: "村", kun: "むら", on: "ソン", imi: "むら", en: "village", group: "Places", mnemonic: "A “tree” on the left and a “street sign/nail” structure on the right." },
    { kanji: "中", kun: "なか", on: "チュウ・ジュウ", imi: "なか", en: "middle / inside", group: "Directions", mnemonic: "A square box with a vertical line cutting directly through the center." },
    { kanji: "虫", kun: "むし", on: "チュウ", imi: "むし", en: "insect", group: "Animals", mnemonic: "A box with a vertical line cutting through it, ending in a horizontal dash with a small dot at the bottom; looks like a stylized bug or a snake with a rattle." },
    { kanji: "行", kun: "いく・おこなう", on: "コウ・ギョウ", imi: "いく", en: "go", group: "Verbs", mnemonic: "A “walking man” shape on the left, and a “street sign/nail” structure on the right; looks like a person walking toward a crossing." },
    { kanji: "良", kun: "よい", on: "リョウ", imi: "よい", en: "good", group: "Descriptions", mnemonic: "A small dot on top of a “Yo” shape, with a vertical tail that hooks up to the right and a small dash; looks like a stylized figure or a machine." },
    { kanji: "食", kun: "たべる", on: "ショク", imi: "たべる", en: "eat", group: "Verbs", mnemonic: "A “person roof” sitting on top of the “Good” character; suggests a person enjoying good food." },
    { kanji: "雨", kun: "あめ", on: "ウ", imi: "あめ", en: "rain", group: "Nature", mnemonic: "A horizontal line on top of an “overturned box” with a vertical “staff” in the middle and four small dashes inside; resembles raindrops falling inside a frame." },
    { kanji: "電", kun: "", on: "デン", imi: "でんき", en: "electricity", group: "Descriptions", mnemonic: "The “Rain” character on top of a box with a long, hooked “fish hook” tail; looks like lightning falling during a storm." },
    { kanji: "外", kun: "そと", on: "ガイ", imi: "そと", en: "outside", group: "Directions", mnemonic: "The “Evening” character on the left and a “Fortune-telling/Rod” shape on the right." },
    { kanji: "北", kun: "きた", on: "ホク・ホッ", imi: "きた", en: "north", group: "Directions", mnemonic: "Two separate, symmetrical structures facing away from each other; looks like two people standing back-to-back." },
    { kanji: "南", kun: "みなみ", on: "ナン", imi: "みなみ", en: "south", group: "Directions", mnemonic: "A “Ten” on top, followed by an “overturned box” containing a dash and two legs, with another “Ten” structure at the very bottom." },
    { kanji: "西", kun: "にし", on: "サイ・セイ", imi: "にし", en: "west", group: "Directions", mnemonic: "A box with a “hat” on top and two internal vertical lines that curve away from each other at the bottom; looks like a container or a stylized face." },
    { kanji: "東", kun: "ひがし", on: "トウ", imi: "ひがし", en: "east", group: "Directions", mnemonic: "A “Sun” character placed inside the middle of a “Tree” character; represents the sun rising through trees." },
    { kanji: "長", kun: "ながい", on: "チョウ", imi: "ながい・おさ", en: "long", group: "Descriptions", mnemonic: "A complex vertical structure with multiple horizontal lines on top and a sweeping base similar to the “Good” character; looks like long hair or a tall, layered object." },

    // Colors
    { kanji: "青", kun: "あおい", on: "セイ", imi: "あお", en: "blue", group: "Colors", mnemonic: "The “Life” character scrunched on top of the “Moon” character." },
    { kanji: "赤", kun: "あかい", on: "セキ", imi: "あか", en: "red", group: "Colors", mnemonic: "A “Soil” or “Dirt” character on top, with a “person’s legs” shape below that has two extra dots; resembles a person over a fire." },

    // Arts
    { kanji: "音", kun: "おと", on: "ON", imi: "おと", en: "sound", group: "Arts", mnemonic: "The “Stand” character positioned on top of the “Sun” character." },

    // Places
    { kanji: "町", kun: "まち", on: "チョウ", imi: "まち", en: "town", group: "Places", mnemonic: "A “field” on the left and a “street sign/nail” structure on the right." },
    { kanji: "村", kun: "むら", on: "ソン", imi: "むら", en: "village", group: "Places", mnemonic: "A “tree” on the left and a “street sign/nail” structure on the right." },
  ],

  N4: [
    // Opposite Pairs
    { kanji: "明", kun: "あかるい", on: "メイ", imi: "あかるい・はっきり", en: "bright / clear", group: "Opposite Pairs", mnemonic: "The sun (日) and the moon (月) shining together are incredibly bright." },
    { kanji: "暗", kun: "くらい", on: "アン", imi: "くらい", en: "dark", group: "Opposite Pairs", mnemonic: "A booming sound (音) blocking out the sun (日), rendering it dark." },
    { kanji: "遠", kun: "とおい", on: "エン", imi: "とおい", en: "far", group: "Opposite Pairs", mnemonic: "Walking (辶) along the road in flowing robes (袁) takes you far away." },
    { kanji: "近", kun: "ちかい", on: "キン", imi: "ちかい", en: "near", group: "Opposite Pairs", mnemonic: "Walking (辶) with an axe (斤) swinging dangerously near you." },
    { kanji: "強", kun: "つよい", on: "キョウ", imi: "つよい", en: "strong", group: "Opposite Pairs", mnemonic: "A highly taut, strong bow (弓) snapping a tough insect (虫)." },
    { kanji: "弱", kun: "よわい", on: "ジャク", imi: "よわい", en: "weak", group: "Opposite Pairs", mnemonic: "Two fragile, broken bows (弓) held together by thin feathers (彡) are weak." },
    { kanji: "重", kun: "おもい", on: "ジュウ", imi: "おもい・だいじな", en: "heavy / important", group: "Opposite Pairs", mnemonic: "A vehicle/car (車) groaning under stacks of heavy luggage." },
    { kanji: "軽", kun: "かるい", on: "ケイ", imi: "かるい", en: "light", group: "Opposite Pairs", mnemonic: "A car (車) constructed purely of thin, delicate thread (圣) is extremely light." },
    { kanji: "太", kun: "ふとい", on: "タイ", imi: "ふとい", en: "fat / thick", group: "Opposite Pairs", mnemonic: "A big person (大) with an extra belly roll (dot) making them fat." },
    { kanji: "細", kun: "ほそい・こまかい", on: "サイ", imi: "ほそい・こまかい", en: "slender / fine", group: "Opposite Pairs", mnemonic: "A delicate silk thread (糸) woven meticulously through the field (田)." },
    { kanji: "良", kun: "よい", on: "リョウ", imi: "よい", en: "good", group: "Opposite Pairs", mnemonic: "A single, good drop of nourishment cleanly dropping into the stomach." },
    { kanji: "悪", kun: "わるい", on: "アク", imi: "わるい", en: "bad", group: "Opposite Pairs", mnemonic: "An inferior, secondary (亜) feeling in your heart (心) is inherently bad." },
    { kanji: "暑", kun: "あつい", on: "ショ", imi: "あつい", en: "hot", group: "Opposite Pairs", mnemonic: "The sun (日) blazing directly over a person (者) outdoors — sweltering hot." },
    { kanji: "寒", kun: "さむい", on: "カン", imi: "さむい", en: "cold", group: "Opposite Pairs", mnemonic: "A person (人) under a roof (宀) surrounded on all sides by ice — shivering cold." },
    { kanji: "借", kun: "かりる", on: "シャク・シャッ", imi: "かりる", en: "borrow", group: "Opposite Pairs", mnemonic: "A person (イ) with former (昔) debts — borrowing from the past." },
    { kanji: "貸", kun: "かす", on: "タイ", imi: "かす", en: "lend", group: "Opposite Pairs", mnemonic: "A former (代) person's shells/money (貝) — lending from one's reserves." },
    { kanji: "始", kun: "はじまる・はじめる", on: "シ", imi: "はじまる", en: "begin / start", group: "Opposite Pairs", mnemonic: "A woman (女) at a platform (台) marks the very beginning." },
    { kanji: "終", kun: "おわる", on: "シュウ", imi: "おわる", en: "end / finish", group: "Opposite Pairs", mnemonic: "Silk thread (糸) coming to its end in winter (冬) — finishing." },
    { kanji: "開", kun: "あける・ひらく", on: "カイ", imi: "あける", en: "open", group: "Opposite Pairs", mnemonic: "Two hands pulling open the gate (門) — opening wide." },
    { kanji: "閉", kun: "しめる・とじる", on: "ヘイ", imi: "しめる", en: "close / shut", group: "Opposite Pairs", mnemonic: "A bolt (才) thrown across the gate (門) — closing it shut." },
    // Adjectives & Modifiers
    { kanji: "低", kun: "ひくい", on: "テイ", imi: "ひくい", en: "low", group: "Adjectives & Modifiers", mnemonic: "A person (イ) bowing to the ground beneath a noble clan (氏), showing low status." },
    { kanji: "広", kun: "ひろい", on: "コウ", imi: "ひろい", en: "spacious / wide", group: "Adjectives & Modifiers", mnemonic: "A vast, sloping roof (广) expanding infinitely outward into spaciousness." },
    { kanji: "短", kun: "みじかい", on: "タン", imi: "みじかい", en: "short", group: "Adjectives & Modifiers", mnemonic: "An arrow (矢) placed next to a tiny bean (豆), emphasizing it is short." },
    { kanji: "正", kun: "ただしい", on: "セイ・ショウ", imi: "ただしい", en: "correct / right", group: "Adjectives & Modifiers", mnemonic: "Coming to a hard stop (止) exactly at the one (一) correct line." },
    { kanji: "変", kun: "かわる・かえる", on: "ヘン", imi: "かわる・へんな", en: "change / strange", group: "Adjectives & Modifiers", mnemonic: "A tangled knot of thread altering and changing (夂) its strange shape." },
    { kanji: "特", kun: "", on: "トク・トッ", imi: "とくべつな", en: "special", group: "Adjectives & Modifiers", mnemonic: "A highly prized, special cow (牛) grazing at the temple (寺)." },
    { kanji: "別", kun: "わかれる", on: "ベツ", imi: "わかれる", en: "separate", group: "Adjectives & Modifiers", mnemonic: "A mouth (口) commanding a sharp knife (刂) to separate ties." },
    { kanji: "急", kun: "いそぐ", on: "キュウ", imi: "いそぐ・きゅうに", en: "hurry / suddenly", group: "Adjectives & Modifiers", mnemonic: "A heavy hand gripping your heart (心), forcing you to hurry in panic." },
    { kanji: "暖", kun: "あたたかい", on: "ダン", imi: "あたたかい", en: "warm", group: "Adjectives & Modifiers", mnemonic: "The sun (日) wrapping its warm arms (爰) around you — warm and cozy." },
    { kanji: "不", kun: "", on: "フ・ブ", imi: "〜ではない", en: "not- (prefix)", group: "Adjectives & Modifiers", mnemonic: "A bird soaring up into the sky, deciding not to come back." },
    { kanji: "有", kun: "ある", on: "ユウ", imi: "ある", en: "exist / have", group: "Adjectives & Modifiers", mnemonic: "A physical hand tightly grasping meat (月), proving it exists." },
    { kanji: "利", kun: "", on: "リ", imi: "りえき", en: "profit / advantage", group: "Adjectives & Modifiers", mnemonic: "Using a knife (刂) to harvest the grain (禾) brings swift profit." },
    { kanji: "便", kun: "たより", on: "ベン・ビン", imi: "べんり・びん", en: "convenience / mail", group: "Adjectives & Modifiers", mnemonic: "A person (イ) actively changing/updating (更) things for convenience." },
    // Colors & Appearance
    { kanji: "赤", kun: "あかい", on: "セキ", imi: "あか", en: "red", group: "Colors & Appearance", mnemonic: "A raging fire (灬) burning intensely under the earth (土) glows red." },
    { kanji: "青", kun: "あおい", on: "セイ", imi: "あお", en: "blue", group: "Colors & Appearance", mnemonic: "Lush, growing vegetation bathed in the blue light of the moon (月)." },
    { kanji: "黒", kun: "くろい", on: "コク", imi: "くろ", en: "black", group: "Colors & Appearance", mnemonic: "A village (里) scorched by a massive fire (灬) turning completely black." },
    { kanji: "色", kun: "いろ", on: "ショク・シキ", imi: "いろ", en: "color", group: "Colors & Appearance", mnemonic: "A kneeling person (巴) beside another (人) — showing vibrant color." },
    { kanji: "形", kun: "かたち", on: "ケイ・ギョウ", imi: "かたち", en: "shape / form", group: "Colors & Appearance", mnemonic: "An open frame (开) stroked three times (彡) — a defined shape." },
    // Seasons & Weather
    { kanji: "春", kun: "はる", on: "シュン", imi: "はる", en: "spring", group: "Seasons & Weather", mnemonic: "Three plants (艹) sprouting over the sun (日) — the warmth of spring." },
    { kanji: "夏", kun: "なつ", on: "カ", imi: "なつ", en: "summer", group: "Seasons & Weather", mnemonic: "A person (夂) dancing beneath the blazing sun — joyful summer." },
    { kanji: "秋", kun: "あき", on: "シュウ", imi: "あき", en: "autumn", group: "Seasons & Weather", mnemonic: "Grain (禾) turning fiery (火) with the brilliant colors of autumn." },
    { kanji: "冬", kun: "ふゆ", on: "トウ", imi: "ふゆ", en: "winter", group: "Seasons & Weather", mnemonic: "Ice crystals (冫) hanging from a thread — things freeze in winter." },
    { kanji: "季", kun: "", on: "キ", imi: "きせつ", en: "season", group: "Seasons & Weather", mnemonic: "Grain (禾) growing over a child (子) — the turning cycle of seasons." },
    { kanji: "節", kun: "ふし", on: "セツ", imi: "くぎり", en: "season / joint", group: "Seasons & Weather", mnemonic: "Bamboo (竹) jointing at the temple (即) — one segment per season." },
    { kanji: "雪", kun: "ゆき", on: "セツ", imi: "ゆき", en: "snow", group: "Seasons & Weather", mnemonic: "Rain (雨) sweeping (彐) softly down as white snow." },
    { kanji: "風", kun: "かぜ", on: "フウ", imi: "かぜ・ふう", en: "wind / style", group: "Seasons & Weather", mnemonic: "An insect (虫) caught in a sail (凡) and blown away by the wind." },
    { kanji: "光", kun: "ひかり・ひかる", on: "コウ", imi: "ひかり", en: "light / shine", group: "Seasons & Weather", mnemonic: "A person (儿) with a flame blazing on their head — glowing with light." },
    // Times of Day & Time Concepts
    { kanji: "朝", kun: "あさ", on: "チョウ", imi: "あさ", en: "morning", group: "Times of Day & Time Concepts", mnemonic: "The sun (日) peeking through the morning mist beside the moon (月) — dawn." },
    { kanji: "昼", kun: "ひる", on: "チュウ", imi: "ひる", en: "noon / daytime", group: "Times of Day & Time Concepts", mnemonic: "The sun (日) passing its highest point — midday." },
    { kanji: "夜", kun: "よる・よ", on: "ヤ", imi: "よる", en: "night", group: "Times of Day & Time Concepts", mnemonic: "A person sheltered under a roof as the dark side (亦) rises — night." },
    { kanji: "夕", kun: "ゆう", on: "", imi: "ゆうがた", en: "evening", group: "Times of Day & Time Concepts", mnemonic: "A half-moon crescent glimpsed at dusk — the evening hour." },
    { kanji: "晩", kun: "", on: "バン", imi: "よる", en: "late evening", group: "Times of Day & Time Concepts", mnemonic: "The sun (日) disappearing as a person (免) runs free — late evening." },
    { kanji: "曜", kun: "", on: "ヨウ", imi: "かがやく", en: "day of week", group: "Times of Day & Time Concepts", mnemonic: "The sun (日) and a bright feathered bird (隹) marking off each day of the week." },
    { kanji: "計", kun: "はかる", on: "ケイ", imi: "はかる", en: "measure / plan", group: "Times of Day & Time Concepts", mnemonic: "Saying words (言) while counting (十) — planning and measuring time." },
    { kanji: "度", kun: "", on: "ド", imi: "ど・ひんど", en: "degree / frequency", group: "Times of Day & Time Concepts", mnemonic: "A hand (又) measuring with a wide ruler (广) — degrees of measure." },
    { kanji: "以", kun: "", on: "イ", imi: "〜から", en: "since / from", group: "Times of Day & Time Concepts", mnemonic: "A person (人) walking with a tool — acting from a certain point on." },
    { kanji: "方", kun: "かた・がた", on: "ホウ", imi: "ほうがく・ほうほう", en: "direction / way", group: "Times of Day & Time Concepts", mnemonic: "A compass needle pointing in a specific direction or way." },
    // Nature — Land & Water
    { kanji: "林", kun: "はやし", on: "リン", imi: "はやし", en: "wood / grove", group: "Nature — Land & Water", mnemonic: "Two trees (木木) standing side by side make a grove." },
    { kanji: "森", kun: "もり", on: "シン", imi: "もり", en: "forest", group: "Nature — Land & Water", mnemonic: "Three trees (木木木) crowded together form a deep forest." },
    { kanji: "地", kun: "", on: "ジ・チ", imi: "じめん", en: "ground / earth", group: "Nature — Land & Water", mnemonic: "The earth (土) spiraling like a snake (也) underfoot — the ground." },
    { kanji: "池", kun: "いけ", on: "チ", imi: "いけ", en: "pond", group: "Nature — Land & Water", mnemonic: "Water (氵) coiling like a snake (也) into a quiet, round pond." },
    { kanji: "海", kun: "うみ", on: "カイ", imi: "うみ", en: "sea", group: "Nature — Land & Water", mnemonic: "Every (每) drop of water (氵) flows together to form the vast sea." },
    { kanji: "洋", kun: "", on: "ヨウ", imi: "おおきいうみ", en: "ocean / Western", group: "Nature — Land & Water", mnemonic: "Water (氵) so grand and endless (羊) it becomes the open ocean." },
    { kanji: "台", kun: "", on: "ダイ・タイ", imi: "だい", en: "platform / stand", group: "Nature — Land & Water", mnemonic: "A mouth (口) raised up on a stand (厶) to make a speech — a platform." },
    // Administrative Areas
    { kanji: "京", kun: "", on: "キョウ", imi: "みやこ", en: "capital", group: "Administrative Areas", mnemonic: "A towering, multi-story pagoda representing the capital city." },
    { kanji: "都", kun: "みやこ", on: "ト・ツ", imi: "みやこ", en: "metropolis", group: "Administrative Areas", mnemonic: "The person (者) thriving in the bustling city boundaries (阝)." },
    { kanji: "府", kun: "", on: "フ", imi: "ふ", en: "admin prefecture", group: "Administrative Areas", mnemonic: "Inside a massive government building (广) handing (付) laws down." },
    { kanji: "県", kun: "", on: "ケン", imi: "けん", en: "prefecture", group: "Administrative Areas", mnemonic: "An eye (目) inspecting a tree from a hanging hook to survey the prefecture." },
    { kanji: "市", kun: "いち", on: "シ", imi: "し・いち", en: "city", group: "Administrative Areas", mnemonic: "A grand market towel (巾) waving above the city streets." },
    { kanji: "区", kun: "", on: "ク", imi: "く", en: "ward", group: "Administrative Areas", mnemonic: "A localized box containing an 'X' to mark the exact ward." },
    { kanji: "町", kun: "まち", on: "チョウ", imi: "まち", en: "town", group: "Administrative Areas", mnemonic: "A rice field (田) positioned beside a street sign (丁) in town." },
    { kanji: "村", kun: "むら", on: "ソン", imi: "むら", en: "village", group: "Administrative Areas", mnemonic: "Trees (木) planted just an inch (寸) apart around the village." },
    // Buildings & Spaces
    { kanji: "所", kun: "ところ・どころ", on: "ショ・ジョ", imi: "ばしょ", en: "place", group: "Buildings & Spaces", mnemonic: "Using an axe (斤) to carve a wooden door (戸) for your place." },
    { kanji: "場", kun: "ば", on: "ジョウ", imi: "ば・ばしょ", en: "place / field", group: "Buildings & Spaces", mnemonic: "The sun (日) rising over the earth (土) marks this open place or field." },
    { kanji: "内", kun: "うち", on: "ナイ", imi: "うち", en: "inside / within", group: "Buildings & Spaces", mnemonic: "A person (人) standing inside an enclosure (冂) — within." },
    { kanji: "院", kun: "", on: "イン", imi: "たてもの", en: "institution / hospital", group: "Buildings & Spaces", mnemonic: "A complete enclosure (阝) sheltering a great institution — the hospital (病院)." },
    // MISSING: 館
    // MISSING: 堂
    // MISSING: 室
    { kanji: "屋", kun: "や", on: "オク", imi: "やね", en: "roof / shop", group: "Buildings & Spaces", mnemonic: "A corpse (尸) resting over a reach (至) — a sheltering rooftop shop." },
    { kanji: "工", kun: "", on: "コウ", imi: "こうじ・こうじょう", en: "craft / construction", group: "Buildings & Spaces", mnemonic: "A ruler measuring between two beams — the mark of a craftsman at work." },
    { kanji: "図", kun: "", on: "ズ・ト", imi: "ず・ちず", en: "diagram / map", group: "Buildings & Spaces", mnemonic: "An enclosure (囗) containing a planned layout (×) — a diagram or map." },
    { kanji: "号", kun: "", on: "ゴウ", imi: "ごう・ばんごう", en: "number / name", group: "Buildings & Spaces", mnemonic: "A mouth (口) calling out from the sky (气) — announcing a number or name." },
    // Body & Health
    { kanji: "体", kun: "からだ", on: "タイ", imi: "からだ", en: "body", group: "Body & Health", mnemonic: "A person (イ) carrying their core root (本) — the foundation of the body." },
    { kanji: "頭", kun: "あたま", on: "ズ", imi: "あたま", en: "head", group: "Body & Health", mnemonic: "A round bean (豆) sitting atop the head page (頁) — your round head." },
    { kanji: "顔", kun: "かお", on: "ガン", imi: "かお", en: "face", group: "Body & Health", mnemonic: "A colorfully patterned page (頁) showing all your features — your face." },
    { kanji: "首", kun: "くび", on: "シュ", imi: "くび・だいいちの", en: "neck / prime", group: "Body & Health", mnemonic: "Hair above (ノ) and a nose/self (自) below — the neck connecting head to body." },
    { kanji: "心", kun: "こころ", on: "シン", imi: "こころ・きもち", en: "heart / feelings", group: "Body & Health", mnemonic: "Three drops of blood pumping outward from the heart — the seat of feelings." },
    { kanji: "声", kun: "こえ", on: "セイ", imi: "こえ", en: "voice", group: "Body & Health", mnemonic: "A scholar (士) grounding (土) their voice — calling out clearly." },
    { kanji: "病", kun: "やまい", on: "ビョウ", imi: "びょうき", en: "illness", group: "Body & Health", mnemonic: "A person lying on a sickbed (疒) stricken by illness." },
    { kanji: "薬", kun: "くすり", on: "ヤク・ヤッ", imi: "くすり", en: "medicine / drug", group: "Body & Health", mnemonic: "Medicinal grass (艹) that brings joy and ease (楽) — healing medicine." },
    { kanji: "科", kun: "", on: "カ", imi: "わけたもの", en: "category / dept", group: "Body & Health", mnemonic: "Grain (禾) measured on a scale (斗) and sorted into departments." },
    { kanji: "医", kun: "", on: "イ", imi: "いがく", en: "medicine / doctor", group: "Body & Health", mnemonic: "A quiver (匸) holding an arrow (矢) — the ancient doctor's healing tool." },
    // Family
    { kanji: "私", kun: "わたし・わたくし", on: "シ", imi: "わたし", en: "I / private", group: "Family", mnemonic: "Grain (禾) coiled and kept for oneself (ム) — my private share." },
    { kanji: "自", kun: "みずから", on: "シ・ジ", imi: "じぶん", en: "self / oneself", group: "Family", mnemonic: "A nose shape — in Japanese, pointing to one's nose means 'myself'." },
    { kanji: "家", kun: "いえ・や", on: "カ・ケ", imi: "いえ", en: "home / house", group: "Family", mnemonic: "A pig (豕) living under a roof (宀) — that's a home in ancient times." },
    { kanji: "族", kun: "", on: "ゾク", imi: "いちぞく", en: "tribe / family", group: "Family", mnemonic: "An arrow (矢) flying from a banner (方) — a clan rallying under one flag." },
    { kanji: "親", kun: "おや・したしい", on: "シン", imi: "おや・したしい", en: "parent / close", group: "Family", mnemonic: "Standing on a tree (立+木), watching (見) closely — a parent's close attention." },
    { kanji: "両", kun: "", on: "リョウ", imi: "りょうほう", en: "both", group: "Family", mnemonic: "A cart with two wheels on both sides — representing both." },
    { kanji: "兄", kun: "あに", on: "ケイ・キョウ", imi: "あに", en: "elder brother", group: "Family", mnemonic: "A mouth (口) on top of legs (儿) — the elder brother who speaks first." },
    { kanji: "弟", kun: "おとうと", on: "ダイ", imi: "おとうと", en: "younger brother", group: "Family", mnemonic: "A bow (弓) with a stake and thread — the younger brother tied behind." },
    { kanji: "姉", kun: "あね", on: "シ", imi: "あね", en: "elder sister", group: "Family", mnemonic: "A woman (女) with a city (市) behind her — the elder sister who leads." },
    { kanji: "妹", kun: "いもうと", on: "マイ", imi: "いもうと", en: "younger sister", group: "Family", mnemonic: "A woman (女) not yet mature (未) — the younger sister." },
    // Society & Work
    { kanji: "者", kun: "もの", on: "シャ", imi: "ひと", en: "person / expert", group: "Society & Work", mnemonic: "An elder person (老) speaking at a gathering — the recognized expert." },
    { kanji: "員", kun: "", on: "イン", imi: "なかま", en: "member", group: "Society & Work", mnemonic: "A mouth (口) on top of the shells (貝), counting every member." },
    { kanji: "民", kun: "", on: "ミン", imi: "ひとびと", en: "people / nation", group: "Society & Work", mnemonic: "A person (ノ) with an eye struck shut (氏) — the common people." },
    { kanji: "主", kun: "おもな・ぬし", on: "シュ", imi: "おもな・しゅじん", en: "main / master", group: "Society & Work", mnemonic: "A lamp flame (丶) standing on a king's pillar (王) — the master at the center." },
    { kanji: "同", kun: "おなじ", on: "ドウ", imi: "おなじ", en: "same", group: "Society & Work", mnemonic: "A shared mouth (口) inside the same enclosure (冂) — all the same." },
    { kanji: "仕", kun: "つかえる", on: "シ", imi: "つかえる", en: "serve", group: "Society & Work", mnemonic: "A person (イ) standing tall as a samurai (士) ready to serve." },
    { kanji: "事", kun: "こと", on: "ジ", imi: "こと", en: "matter / thing", group: "Society & Work", mnemonic: "A busy hand grasping a stick through a box, managing a difficult matter." },
    { kanji: "働", kun: "はたらく", on: "ドウ", imi: "はたらく", en: "work / labor", group: "Society & Work", mnemonic: "A person (イ) using heavy (重) force and power (力) — working hard." },
    { kanji: "業", kun: "", on: "ギョウ", imi: "わざ", en: "deed / industry", group: "Society & Work", mnemonic: "Two crossed tree trunks (業) representing the industry of many hands." },
    { kanji: "産", kun: "うむ", on: "サン", imi: "つくる", en: "produce / birth", group: "Society & Work", mnemonic: "A person standing on fertile land (生) producing new things — birth and production." },
    { kanji: "銀", kun: "", on: "ギン", imi: "ぎん", en: "silver", group: "Society & Work", mnemonic: "Pure, good (艮) metal (金) shining like silver." },
    { kanji: "世", kun: "よ", on: "セ・セイ", imi: "せかい・せだい", en: "world / generation", group: "Society & Work", mnemonic: "Three connected branches symbolizing continuous generations in this world." },
    { kanji: "界", kun: "", on: "カイ", imi: "さかいめ", en: "boundary / world", group: "Society & Work", mnemonic: "Farm fields (田) wedged (介) together perfectly to define a boundary." },
    // Food & Eating
    // MISSING: 米
    { kanji: "飯", kun: "めし", on: "ハン", imi: "めし・ごはん", en: "meal / cooked rice", group: "Food & Eating", mnemonic: "Eating (食) something turned and cooked (反) — a cooked rice meal." },
    { kanji: "肉", kun: "にく", on: "ニク", imi: "にく", en: "meat / flesh", group: "Food & Eating", mnemonic: "Two people (人人) packed inside an enclosure — meat packed tightly." },
    // MISSING: 鳥
    { kanji: "野", kun: "の", on: "ヤ", imi: "の・やさい", en: "field / wild", group: "Food & Eating", mnemonic: "Rice fields (里) beside storage (予) — the wild open fields of vegetables." },
    { kanji: "菜", kun: "な", on: "サイ", imi: "やさい", en: "vegetable / greens", group: "Food & Eating", mnemonic: "A plant (艹) gathered by a hand (采) from the tree — fresh vegetables." },
    { kanji: "茶", kun: "", on: "チャ・サ", imi: "ちゃいろ・おちゃ", en: "brown / tea", group: "Food & Eating", mnemonic: "Leaves picked from a plant (艹) sprouting above a tree (木) and person — brewing tea." },
    { kanji: "味", kun: "あじ", on: "ミ", imi: "あじ・いみ", en: "taste / flavor / meaning", group: "Food & Eating", mnemonic: "A mouth (口) tasting the unknown (未) — savoring something new." },
    // MISSING: 料
    // MISSING: 理
    // Everyday Objects
    { kanji: "物", kun: "もの", on: "ブツ・モツ", imi: "もの", en: "thing / object", group: "Everyday Objects", mnemonic: "A cow (牛) and scattered pieces (勿) — all the things around us." },
    { kanji: "品", kun: "しな", on: "ヒン", imi: "しな", en: "goods / item", group: "Everyday Objects", mnemonic: "Three boxes (口口口) stacked — many goods on display." },
    { kanji: "服", kun: "", on: "フク", imi: "ふく・したがう", en: "clothes / obey", group: "Everyday Objects", mnemonic: "A moon/flesh (月) shape folded (卩) — clothes wrapping the body." },
    { kanji: "犬", kun: "いぬ", on: "ケン", imi: "いぬ", en: "dog", group: "Everyday Objects", mnemonic: "A big person (大) with a tiny dot — a loyal dog companion." },
    { kanji: "紙", kun: "かみ", on: "シ", imi: "かみ", en: "paper", group: "Everyday Objects", mnemonic: "Silk thread (糸) pressed flat by a clan (氏) — making paper." },
    { kanji: "元", kun: "もと", on: "ゲン・ガン", imi: "もと", en: "origin", group: "Everyday Objects", mnemonic: "Two strong, foundational legs acting as the origin of all movement." },
    { kanji: "切", kun: "きる・きっ", on: "セツ", imi: "きる", en: "cut", group: "Everyday Objects", mnemonic: "Taking the number seven (七) and using a knife (刀) to cut it." },
    { kanji: "好", kun: "すき", on: "コウ", imi: "すき", en: "like / fond", group: "Everyday Objects", mnemonic: "A woman (女) holding her beloved child (子) because she likes them." },
    // Movement & Motion
    { kanji: "止", kun: "とまる", on: "シ", imi: "とまる", en: "stop", group: "Movement & Motion", mnemonic: "A single footstep pressed into the ground — stopped in its tracks." },
    { kanji: "歩", kun: "あるく", on: "ホ・ボ", imi: "あるく", en: "walk", group: "Movement & Motion", mnemonic: "A foot (止) stepping above another footprint (少) — walking step by step." },
    { kanji: "走", kun: "はしる", on: "ソウ", imi: "はしる", en: "run", group: "Movement & Motion", mnemonic: "A person (大) with soil (土) under their feet — running forward." },
    { kanji: "起", kun: "おきる・おこす", on: "キ", imi: "おきる", en: "get up / wake", group: "Movement & Motion", mnemonic: "A person rising (走) up over themselves (己) — getting up." },
    { kanji: "動", kun: "うごく", on: "ドウ", imi: "うごく", en: "move", group: "Movement & Motion", mnemonic: "Heavy/important (重) force and power (力) needed to move." },
    { kanji: "帰", kun: "かえる", on: "キ", imi: "かえる", en: "return home", group: "Movement & Motion", mnemonic: "A broom (帚) sweeping the path home — returning." },
    { kanji: "去", kun: "さる", on: "キョ", imi: "すぎた・さる", en: "past / leave", group: "Movement & Motion", mnemonic: "Standing up (土) and going away (ム) — departing into the past." },
    // MISSING: 死
    // Transport & Travel
    { kanji: "乗", kun: "のる", on: "ジョウ", imi: "のる", en: "ride / board", group: "Transport & Travel", mnemonic: "A person jumping onto a tree (木) to ride it — boarding." },
    // MISSING: 降
    { kanji: "運", kun: "はこぶ", on: "ウン", imi: "はこぶ・うん", en: "carry / luck", group: "Transport & Travel", mnemonic: "Moving along (辶) with an army (軍) — carrying goods with luck." },
    { kanji: "転", kun: "ころぶ・まわる", on: "テン", imi: "ころぶ", en: "roll / fall / transfer", group: "Transport & Travel", mnemonic: "A car (車) that slips and turns (専) — rolling and transferring." },
    { kanji: "発", kun: "", on: "ハツ・ホッ", imi: "はっしゃ・でる", en: "start / emit / depart", group: "Transport & Travel", mnemonic: "Legs rising (癶) as a bow (弓) is launched — departing, starting off." },
    { kanji: "着", kun: "きる・つく", on: "チャク", imi: "きる・つく", en: "wear / arrive", group: "Transport & Travel", mnemonic: "A sheep (羊) resting with an eye (目) — arriving clothed and settled." },
    { kanji: "通", kun: "とおる・かよう", on: "ツウ", imi: "とおる", en: "pass through / commute", group: "Transport & Travel", mnemonic: "Walking (辶) the same drum path (甬) every day — commuting through." },
    { kanji: "交", kun: "まじわる", on: "コウ", imi: "まじわる・こうつう", en: "exchange / traffic", group: "Transport & Travel", mnemonic: "A person crossing their arms at a junction — the crossroads of exchange." },
    { kanji: "旅", kun: "たび", on: "リョ", imi: "たび", en: "trip / travel", group: "Transport & Travel", mnemonic: "People clustering under a waving flag on a guided trip." },
    // Daily Actions
    { kanji: "住", kun: "すむ", on: "ジュウ", imi: "すむ", en: "live", group: "Daily Actions", mnemonic: "A person (イ) living right next to their master (主)." },
    { kanji: "持", kun: "もつ", on: "ジ", imi: "もつ", en: "have / hold", group: "Daily Actions", mnemonic: "A hand (手) gripping a temple (寺) — holding on firmly." },
    { kanji: "待", kun: "まつ", on: "タイ", imi: "まつ", en: "wait", group: "Daily Actions", mnemonic: "A person walking (彳) and watching a temple (寺) — waiting patiently." },
    { kanji: "活", kun: "", on: "カツ", imi: "いきいき", en: "lively / active", group: "Daily Actions", mnemonic: "Water (氵) flowing with a tongue (舌) — lively and active." },
    { kanji: "回", kun: "まわす・まわる", on: "カイ", imi: "まわる", en: "turn / time", group: "Daily Actions", mnemonic: "A spiral path inside a box — going around and around." },
    { kanji: "使", kun: "つかう", on: "シ", imi: "つかう", en: "use", group: "Daily Actions", mnemonic: "A person (イ) commanding an officer (吏) — putting someone to use." },
    { kanji: "作", kun: "つくる", on: "サク", imi: "つくる", en: "make / create", group: "Daily Actions", mnemonic: "A person (イ) working with a saw (乍) — making something." },
    // MISSING: 化
    { kanji: "代", kun: "かわる", on: "ダイ・タイ", imi: "かわり・じだい", en: "substitute / generation", group: "Daily Actions", mnemonic: "A person (イ) wielding a weapon (弋) — standing in as a substitute." },
    // MISSING: 信
    // MISSING: 進
    { kanji: "送", kun: "おくる", on: "ソウ", imi: "おくる", en: "send", group: "Daily Actions", mnemonic: "Walking (辶) together holding a torch — sending someone off." },
    { kanji: "返", kun: "かえす", on: "ヘン", imi: "かえす", en: "return (something)", group: "Daily Actions", mnemonic: "Walking back (辶) while reversing (反) — returning something." },
    { kanji: "洗", kun: "あらう", on: "セン", imi: "あらう", en: "wash", group: "Daily Actions", mnemonic: "Water (氵) flowing around the foot/ahead (先) — washing clean." },
    { kanji: "注", kun: "そそぐ", on: "チュウ", imi: "そそぐ・ちゅうい", en: "pour / note / attention", group: "Daily Actions", mnemonic: "Water (氵) directed at a master (主) — pouring carefully, noting everything." },
    { kanji: "建", kun: "たてる", on: "ケン", imi: "たてる・たてもの", en: "build / construct", group: "Daily Actions", mnemonic: "A brush (聿) drawing along the road (廴) — building something new." },
    { kanji: "集", kun: "あつまる・あつめる", on: "シュウ", imi: "あつまる", en: "gather / collect", group: "Daily Actions", mnemonic: "Many birds (隹) gathered on a tree (木) — a flock collecting." },
    { kanji: "売", kun: "うる", on: "バイ", imi: "うる", en: "sell", group: "Daily Actions", mnemonic: "A scholar hat (士) over an eye (目) — the merchant watching to sell." },
    { kanji: "引", kun: "ひく", on: "イン", imi: "ひく", en: "pull", group: "Daily Actions", mnemonic: "A bow (弓) drawn back with a stroke — pulling and drawing." },
    // Language & Media
    // MISSING: 漢
    { kanji: "字", kun: "", on: "ジ", imi: "もじ", en: "character / letter", group: "Language & Media", mnemonic: "A child (子) learning under a roof (宀) — mastering characters." },
    { kanji: "文", kun: "ふみ", on: "ブン・モン", imi: "ぶんしょう", en: "sentence / writing", group: "Language & Media", mnemonic: "A crossroads of strokes forming a literary mark — a written character." },
    { kanji: "音", kun: "おと", on: "オン", imi: "おと", en: "sound", group: "Language & Media", mnemonic: "Standing proudly (立) on top of the sun (日) emitting a loud sound." },
    { kanji: "映", kun: "うつす", on: "エイ", imi: "うつす", en: "reflect / project", group: "Language & Media", mnemonic: "The bright sun (日) sitting perfectly in the center (央) to reflect its light." },
    { kanji: "画", kun: "", on: "ガ・カク", imi: "え", en: "picture / drawing", group: "Language & Media", mnemonic: "Lush fields (田) neatly bordered by an elegant frame like a picture." },
    { kanji: "写", kun: "うつす", on: "シャ", imi: "うつす", en: "copy / photograph", group: "Language & Media", mnemonic: "Sitting under a roof (冖) producing and giving (与) a precise copy." },
    { kanji: "真", kun: "ま", on: "シン", imi: "ほんとう", en: "truth / real", group: "Language & Media", mnemonic: "Ten (十) vigilant eyes (目) focusing on the pedestal of truth." },
    { kanji: "歌", kun: "うた・うたう", on: "カ", imi: "うた", en: "song", group: "Language & Media", mnemonic: "Two brothers standing side-by-side, yawning (欠) to project a loud song." },
    { kanji: "楽", kun: "たのしい", on: "ガク・ラク", imi: "たのしい・かんたん", en: "enjoyable / music", group: "Language & Media", mnemonic: "Sparkling white (白) lights decorated on a wooden tree (木) are enjoyable." },
    // Learning & Thinking
    { kanji: "教", kun: "おしえる", on: "キョウ", imi: "おしえる", en: "teach / tell", group: "Learning & Thinking", mnemonic: "Old filial ways (孝) struck with a rod (攵) — disciplined teaching." },
    { kanji: "勉", kun: "", on: "ベン", imi: "べんきょう", en: "study diligently", group: "Learning & Thinking", mnemonic: "A rabbit (免) using force (力) to push through — studying hard." },
    { kanji: "習", kun: "ならう", on: "シュウ", imi: "ならう", en: "learn / practice", group: "Learning & Thinking", mnemonic: "A young bird (羽) practicing over a white sheet (白) — learning by repetition." },
    { kanji: "英", kun: "", on: "エイ", imi: "えいご・すぐれた", en: "England / excellent", group: "Learning & Thinking", mnemonic: "Grass (艹) perfectly centered (央) — standing out as excellent." },
    { kanji: "考", kun: "かんがえる", on: "コウ", imi: "かんがえる", en: "think / consider", group: "Learning & Thinking", mnemonic: "An old man (老) bent in thought with a hook at the end — deeply considering." },
    { kanji: "研", kun: "とぐ", on: "ケン", imi: "けんきゅう", en: "research / polish", group: "Learning & Thinking", mnemonic: "A stone (石) ground open (开) — polishing away to research." },
    { kanji: "究", kun: "きわめる", on: "キュウ", imi: "きわめる", en: "investigate / complete", group: "Learning & Thinking", mnemonic: "A cave (穴) twisted nine ways (九) — searching to the ultimate depth." },
    { kanji: "問", kun: "とう", on: "モン", imi: "もんだい", en: "question / problem", group: "Learning & Thinking", mnemonic: "A mouth (口) knocking at the gate (門) — asking a question." },
    { kanji: "題", kun: "", on: "ダイ", imi: "だいもく・もんだい", en: "subject / title", group: "Learning & Thinking", mnemonic: "A kingly truth (是) displayed above the head (頁) — the title on top." },
    { kanji: "試", kun: "こころみる", on: "シ", imi: "こころみる・しけん", en: "try / test", group: "Learning & Thinking", mnemonic: "Words (言) tested with a ceremonial weapon (式) — formal attempts." },
    { kanji: "験", kun: "", on: "ケン", imi: "しけん・けいけん", en: "experience / exam", group: "Learning & Thinking", mnemonic: "A horse (馬) running through many hurdles (僉) — experiencing an exam." },
    // MISSING: 質
    // MISSING: 合
    { kanji: "答", kun: "こたえる", on: "トウ", imi: "こたえる", en: "answer", group: "Learning & Thinking", mnemonic: "A bamboo scroll (竹) joined with understanding (合) — the answer is within." },
    // MISSING: 用
    { kanji: "意", kun: "", on: "イ", imi: "い・きもち", en: "meaning / will / feeling", group: "Learning & Thinking", mnemonic: "A sound (音) over the heart (心) — the meaning felt deep inside." },
    { kanji: "知", kun: "しる", on: "チ", imi: "しる", en: "know / be aware", group: "Learning & Thinking", mnemonic: "An arrow (矢) shot into a mouth (口) hits exactly what you know." },
    // MISSING: 説
    { kanji: "思", kun: "おもう", on: "シ", imi: "おもう", en: "think / feel", group: "Learning & Thinking", mnemonic: "The field (田) of your mind over the heart (心) — thinking deeply." },

  ]
};

function getKanjiGroups(level) {
  const seen = new Set();
  return (KANJI[level] || []).reduce((acc, k) => {
    if (!seen.has(k.group)) { seen.add(k.group); acc.push(k.group); }
    return acc;
  }, []);
}

function getKanjiByGroup(level, group) {
  const all = KANJI[level] || [];
  return group === 'all' ? all : all.filter(k => k.group === group);
}

function getKanjiGroupCount(level, group) {
  return getKanjiByGroup(level, group).length;
}
